// GENERATED by web/scripts/gen-markets.mjs from ops/markets/tier1.json — do not edit.
//
// Regenerate with `pnpm --filter @callhouse/web gen:markets` after the registry changes, and
// commit the result: the Docker build context has no ops/, so this file IS the registry as far
// as the app is concerned. lib/markets.test.ts fails when it drifts from tier1.json.
// lib/markets.ts is the typed, filtered view every page reads; nothing imports this file directly
// except that module and lib/contracts.ts (for the default market's compiled-in addresses).

/** The registry build this file was generated from. */
export const GENERATED_REGISTRY = {
  verifiedAtBlock: 70185885,
  generatedAt: "2026-09-23T03:18:22.394Z",
} as const;

/** Every market in the registry, live or not, in registry order. */
export const GENERATED_MARKETS = [
  {
    ticker: "NVDA",
    name: "NVIDIA • Robinhood Token",
    asset: "0xd0601CE157Db5bdC3162BbaC2a2C8aF5320D9EEC",
    feed: "0x379EC4f7C378F34a1B47E4F3cbeBCbAC3E8E9F15",
    factory: "0xc4A5Cd0DE91CaB7F5Ebe2114bc63Fbb43E642BBb",
    deployBlock: 64038234,
    status: "live",
    wave: "live",
    mode: "vol",
    cboeRoot: "NVDA",
    depositCapUsd: null,
    v1FrozenAt: null,
    v2: {
      status: "live",
      wave: "canary",
      strikeTick: "2500000",
      puts: false,
      mintFeePpm: 0,
      univ3Pool: "0xd4EB21209C4D6093f80B5b84f5C45cc093EA14a3",
      univ3MinLiquidity: "1700000000000000000",
      dataStreamsFeedId: "0x000b6aa036224454037bab103184565f6aa9ea589c3b349f6d8471ee753524b9",
      payoutRoute: {
        venue: "v3",
        fee: 500,
      },
      overrides: {
        dailyWeekdays: ["mon", "wed", "fri"],
      },
      houseVault: "0xF9F95d999aA798fc0B60a0f85f7CCe251fe247a7",
      house: {
        weekly: null,
        daily: "0xF9F95d999aA798fc0B60a0f85f7CCe251fe247a7",
      },
      registeredAt: 1790363419,
      registerTx: "0x592bc0b07598834d5b824042d639e5fd2552d5979c312e9c14055c1cb12558aa",
      chainlinkBand: {
        minPrice: "20000000",
        maxPrice: "2000000000",
      },
    },
  },
  {
    ticker: "SPCX",
    name: "SpaceX • Robinhood Token",
    asset: "0x4a0E65A3EcceC6dBe60AE065F2e7bb85Fae35eEa",
    feed: "0xB265810950ba6c5C0Ff821c9963014a56fD8Bffb",
    factory: null,
    deployBlock: null,
    status: "superseded-by-v2",
    wave: "wave2",
    mode: "vol",
    cboeRoot: "SPCX",
    depositCapUsd: 10000,
    v1FrozenAt: null,
    v2: {
      status: "live",
      wave: "wave1",
      strikeTick: "1000000",
      puts: false,
      mintFeePpm: 0,
      univ3Pool: "0xc61284332117c3FB23A2A56cceFFD07F7aF60029",
      univ3MinLiquidity: "1300000000000000000",
      dataStreamsFeedId: "0x000b4f3c6cbfd4f0ba9c635b5dd3b188338c98a3f6b595615ddfdb3a75dee647",
      payoutRoute: {
        venue: "v3",
        fee: 500,
      },
      overrides: {
        expiriesAhead: {
          weekly: 2,
          daily: 0,
        },
      },
      houseVault: "0x031AB8C376C31447e766Fb95d19D2369f3806Ce1",
      house: {
        weekly: null,
        daily: "0x031AB8C376C31447e766Fb95d19D2369f3806Ce1",
      },
      registeredAt: 1790363436,
      registerTx: "0x4078cb36067b8d5b3c1c2e4fe5dda2a14a94b7bdc73ec842e023985f82a1d439",
      chainlinkBand: {
        minPrice: "20000000",
        maxPrice: "1000000000",
      },
    },
  },
] as const;

/** The registry's top-level v2 block: the interface version it follows and the v2 deploy block (null until deployed). */
export const V2_REGISTRY = {
  interfaceVersion: 8,
  deployBlock: 72462898,
} as const;

/** v2 contract addresses, as the registry has them; null until the v2 deploy writes them back. */
export const V2_CONTRACTS = {
  clearinghouse: "0xD33663CD8A363710daF87C78616899cED34b9374",
  orderBook: "0x581AFCC6Da498F4D8161705E1D294a6e4fEeaeF3",
  settlementOracle: "0x932c9BF2350633382ed6b2CB52e1c82345A3B160",
  expiryCalendar: "0x7ae41B8b0ba2189CC59a9c124b20D9BA00177ae5",
  keeperRewards: "0x7410FcBE201f40a731336B723E510B9131229Eb1",
  autoRoller: "0x47dE4E61C10d3508505594575404086C5941EeD2",
  payoutAdapter: "0x92E01EbED9A3253a7D029912546C594bD3DD2737",
  makerVault: "0x491D26c3c3C2Eb36e9D7629f5bd6C16344972A28",
  makerRegistry: "0xeCD6F1842E292A2B93288bb22Ac318871d7C8B1f",
  rewardsDistributor: "0x54545581d614C40bbD4942b527d463402eb446f6",
  accessManager: "0x3698FDcD6A29675382d287b30546B75dE9174103",
  houseVault: "0xF9F95d999aA798fc0B60a0f85f7CCe251fe247a7",
  houseVaultFactory: "0x4626da1A3fCf06d837dBD49708C7B658DFD08843",
  hedger: null,
  rewardsDistributorLender: null,
  earnVault: "0x847794900FAE91516Cc3fbc36955C6B64a2dD609",
  stockVenueAdapter: null,
  stockZap: "0x0E3C7Ea59d89D6BE8bB6Af5706856C4E913a0FE7",
  sources: {
    chainlink: "0xC01067D7fb962AB6374DCe20E98b1DdC9086780a",
    univ3: "0x1E2F642C8DA800ffc5c7898DF7d28A1DBfE0f70C",
    dataStreams: "0x459a09Ea21156de69849522B1599a9e5deEF24A6",
  },
} as const;

/** Uniswap v3 periphery on 4663 (payout conversion). */
export const V2_UNISWAP_V3 = {
  factory: "0x1f7d7550B1b028f7571E69A784071F0205FD2EfA",
  swapRouter02: "0xCaf681a66D020601342297493863E78C959E5cb2",
  quoterV2: "0x33e885eD0Ec9bF04EcfB19341582aADCb4c8A9E7",
} as const;

/** Launch fee parameters (bps; takerFeeFlat in USDG base units, a decimal string). The contracts hold the live values. */
export const V2_FEES = {
  premiumFeeBps: 500,
  mintFeePpm: 0,
  allowRent: false,
  resaleFeeBps: 0,
  takerFeeFlat: "100000",
  takerFeeCapBps: 1000,
  makerRebateBps: 5000,
  exerciseFeeBps: 25,
  payoutSlippageBps: 30,
} as const;

/** Market defaults: oracle bounds, strike ladders per tenor, expiries listed ahead. A market's v2.overrides replaces keys of these. */
export const V2_DEFAULTS = {
  maxDeviationBps: 150,
  uncorroboratedDelayS: 21600,
  spotMaxAgeS: 90000,
  maxFeedAgeS: 345600,
  chainlinkMaxStaleS: 93600,
  chainlinkMaxRoundJumpBps: 2000,
  univ3WindowS: 300,
  ladder: {
    weekly: {
      rungs: 5,
      firstOtmBps: 200,
      stepBps: 200,
      cardTargetBps: 400,
    },
    daily: {
      rungs: 5,
      firstOtmBps: 100,
      stepBps: 100,
      cardTargetBps: 200,
    },
  },
  expiriesAhead: {
    weekly: 0,
    daily: 6,
  },
  dailyWeekdays: ["mon", "tue", "wed", "thu", "fri"],
} as const;

/** The launch set: the ONLY markets the app may present as launching. Not derived from wave or status; see the note. */
export const LAUNCH_SET = {
  note: "The v8 launch set: launch is NVDA and SPCX only. This is the AUTHORITATIVE list and it is deliberately NOT derived from `wave` or `status`. Waves mean rollout ORDER and no market moves bucket for this; the two fields answer different questions and a tool that infers the launch set from either gets a different answer. `markets` names tickers that must exist in `markets[]`; build-markets.mjs validates that and preserves this block across a rebuild.",
  markets: ["NVDA", "SPCX"],
} as const;
