/**
 * The strike picker and the sizer, pinned integer for integer against contracts/src/Policy.sol.
 *
 * WHY THIS FILE EXISTS: every number policy.ts produces is re-derived on chain by the vault, and
 * the vault's answer wins. A picker that is one base unit under the premium floor, or one rung
 * outside the band, is a `PremiumBelowMinimum` or `StrikeBelowBand` revert at 20:00 UTC on a
 * Friday — the keeper's simulation catches it, but the week is still unwritten. These tests pin
 * the maths to the values the contracts compute, using the real cycle-1 NVDA ladder and the real
 * Chainlink print from 2026-09-12 so the fixtures are numbers that actually occurred.
 *
 * The fee-split vectors are generated by the SAME linear congruential generator, seed and loop as
 * contracts/test/unit/SplitDiff.t.sol. Change one side and the other must change with it.
 *
 * DELIBERATELY ABSENT: no RPC and no HTTP. `readLastFill` is injected through the seam on
 * PickInput, so nothing here dials Overcall, and the RPC in the environment is a discard port.
 */
import assert from 'node:assert/strict';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test } from 'node:test';

/* ---- environment first: config.ts validates process.env the moment it is imported ---- */
const scratch = mkdtempSync(join(tmpdir(), 'callhouse-keeper-policy-'));
process.env.KEEPER_ENV_FILE = '/dev/null'; // never read a developer's .env into a test
process.env.RH_RPC = 'http://127.0.0.1:9'; // the discard port; nothing here dials it
process.env.REGISTRY = '0x8E973cE1A6884E28Ad3E377d5f670Bc0b463f4EA';
process.env.VAULT = '0x1111111111111111111111111111111111111111';
process.env.KEEPER_PK = `0x${'11'.repeat(32)}`;
process.env.KEEPER_DB_PATH = join(scratch, 'keeper.db');
process.env.KEEPER_LOG_LEVEL = 'fatal';
delete process.env.KEEPER_UNIT_PRICE_USDG6;
delete process.env.PREMIUM_MARGIN_BPS; // the default (0) unless a test passes the seam
delete process.env.RH_RPC_2;

const { BPS } = await import('./config.js');
const {
  LAST_FILL_MAX_LIFT,
  ceilDiv,
  liftedUnitPrice6,
  maxContracts,
  minUnitPrice6,
  pickWrite,
  relistUnitPrice6,
  strikeBand,
  withPremiumMargin,
} = await import('./policy.js');
const { MIN_LISTABLE_UNIT_PRICE_6, OVERCALL_FEE_BPS, splitPremium } = await import('./seaport.js');
type PolicyParams = import('./policy.js').PolicyParams;
type Rung = import('./policy.js').Rung;
type CycleView = import('./policy.js').CycleView;

/*//////////////////////////////////////////////////////////////
                              FIXTURES
//////////////////////////////////////////////////////////////*/

/** Policy.launchDefaults(), and README "Policy (launch)". */
const LAUNCH: PolicyParams = {
  minOtmBps: 300n,
  maxOtmBps: 1200n,
  minPremiumBps: 40n,
  maxUtilizationBps: 9500n,
  protocolFeeBps: 500n,
  maxContractsCap: 50n,
};

/** Chainlink RHNVDA/USD, 8 dp, read 2026-09-12: 21829793457 -> 218.297934 USDG per lot. */
const SPOT = 218_297_934n;

/** The real cycle-1 NVDA ladder: ids from registry.cycle().optionIds, strikes from
 *  strikePerContract(), read 2026-09-12. Strikes ascend 226..246 USDG in 5-dollar rungs. */
const LADDER: Array<[bigint, bigint]> = [
  [113025628429828481228850936737953628080486640605422851339090182744894714413056n, 226_000_000n],
  [29652592033419692000166847561911668028189801263392568326594311383797020491776n, 231_000_000n],
  [13956151908388063551378518883460877979717043668997816139085862263440384458752n, 236_000_000n],
  [8012928620938394388054169085135774622795258770514699139381494411582911807488n, 241_000_000n],
  [56885395977254369119998982131173877604217583767740146085872832926902011297792n, 246_000_000n],
];

const CYCLE: CycleView = {
  number: 1,
  exerciseTimestamp: 1789761600n, // 2026-09-18 20:00 UTC, Friday book close
  expiryTimestamp: 1789848000n, // 2026-09-19 20:00 UTC
  lotSize: 1_000_000_000_000_000_000n,
  optionIds: LADDER.map(([id]) => id),
};

/** The ladder as policy.readRungs() returns it: sorted ascending, approved, in the live cycle. */
function rungs(overrides: Partial<Record<number, Partial<Rung>>> = {}): Rung[] {
  return LADDER.map(([optionId, strikeUsdg6], index) => ({
    optionId,
    strikeUsdg6,
    approved: true,
    cycleOf: 1,
    ...overrides[index],
  }));
}

const noFill = async (): Promise<bigint | null> => null;

function pick(overrides: Partial<Parameters<typeof pickWrite>[0]> = {}) {
  return pickWrite({
    cycle: CYCLE,
    rungs: rungs(),
    policy: LAUNCH,
    idleAssets: 25_000_000_000_000_000_000n, // 25 NVDA
    spotUsdg6: SPOT,
    readLastFill: noFill,
    unitPriceOverride6: null,
    ...overrides,
  });
}

/*//////////////////////////////////////////////////////////////
                              THE BAND
//////////////////////////////////////////////////////////////*/

test('strikeBand floors both ends exactly as Policy.strikeBand does', () => {
  // 218297934 * 10300 / 10000 = 224846872.02 -> 224846872; * 11200 / 10000 = 244493686.08.
  assert.deepEqual(strikeBand(SPOT, LAUNCH), { lo: 224_846_872n, hi: 244_493_686n });
  // Whole-dollar spots, checked by hand: the band is inclusive on both ends.
  assert.deepEqual(strikeBand(200_000_000n, LAUNCH), { lo: 206_000_000n, hi: 224_000_000n });
  assert.deepEqual(strikeBand(225_000_000n, LAUNCH), { lo: 231_750_000n, hi: 252_000_000n });
});

test('pickWrite takes the nearest rung INSIDE the band, not the nearest rung', async () => {
  // Spot 218.30: band [224.85, 244.49]; 226 is the nearest OTM rung and it is in band.
  const real = await pick();
  assert.ok(real.ok);
  assert.equal(real.strikeUsdg6, 226_000_000n);
  assert.equal(real.optionId, LADDER[0]?.[0]);
  assert.equal(real.bandLowUsdg6, 224_846_872n);
  assert.equal(real.bandHighUsdg6, 244_493_686n);

  // Spot 225: band [231.75, 252]. 226 and 231 are nearer to spot but BELOW the band;
  // 236 is the lowest eligible strike and must be the pick.
  const shifted = await pick({ spotUsdg6: 225_000_000n });
  assert.ok(shifted.ok);
  assert.equal(shifted.strikeUsdg6, 236_000_000n);

  // Spot 210: band [216.3, 235.2] -> 226 and 231 eligible, 226 is nearest.
  const lower = await pick({ spotUsdg6: 210_000_000n });
  assert.ok(lower.ok);
  assert.equal(lower.strikeUsdg6, 226_000_000n);
});

test('pickWrite refuses, with the reason and the ladder, when no rung is in band', async () => {
  // Spot 200: band [206, 224]; every live rung is above it. Spot 300: band [309, 336]; below.
  for (const spotUsdg6 of [200_000_000n, 300_000_000n]) {
    const result = await pick({ spotUsdg6 });
    assert.equal(result.ok, false);
    if (result.ok) return;
    assert.equal(result.reason, 'no-rung-in-band');
    assert.equal(result.detail.strikes, '226000000,231000000,236000000,241000000,246000000');
    assert.equal(result.detail.minOtmBps, '300');
    assert.equal(result.detail.maxOtmBps, '1200');
  }
});

test('pickWrite respects isApproved and cycleOf before it looks at the band', async () => {
  // 226 not approved -> the pick moves to 231, which is still in band.
  const unapproved = await pick({ rungs: rungs({ 0: { approved: false } }) });
  assert.ok(unapproved.ok);
  assert.equal(unapproved.strikeUsdg6, 231_000_000n);

  // 226 belongs to a previous cycle (the registry can leave a stale approval) -> 231.
  const stale = await pick({ rungs: rungs({ 0: { cycleOf: 0 } }) });
  assert.ok(stale.ok);
  assert.equal(stale.strikeUsdg6, 231_000_000n);

  // Nothing in the live cycle at all: refused, and the reported ladder is EMPTY, because a
  // rung that is not approved for this cycle is not a rung the operator could have written.
  const none = await pick({ rungs: rungs({ 0: { cycleOf: 2 }, 1: { cycleOf: 2 }, 2: { approved: false }, 3: { cycleOf: 0 }, 4: { approved: false } }) });
  assert.equal(none.ok, false);
  if (none.ok) return;
  assert.equal(none.reason, 'no-rung-in-band');
  assert.equal(none.detail.strikes, '');
});

test('pickWrite refuses a missing cycle, a zero spot, and no idle collateral', async () => {
  const noCycle = await pick({ cycle: { ...CYCLE, number: 0 } });
  assert.equal(noCycle.ok, false);
  if (!noCycle.ok) assert.equal(noCycle.reason, 'no-cycle');

  const noSpot = await pick({ spotUsdg6: 0n });
  assert.equal(noSpot.ok, false);
  if (!noSpot.ok) assert.equal(noSpot.reason, 'spot-zero');

  // 1 NVDA at 95% utilisation is 0.95 lots, which floors to nothing.
  const dust = await pick({ idleAssets: 1_000_000_000_000_000_000n });
  assert.equal(dust.ok, false);
  if (!dust.ok) assert.equal(dust.reason, 'no-idle-collateral');
});

/*//////////////////////////////////////////////////////////////
                              THE SIZE
//////////////////////////////////////////////////////////////*/

test('maxContracts is floor(idle * 95% / lot), capped at maxContractsCap', () => {
  const lot = CYCLE.lotSize;
  const nvda = (n: number) => BigInt(n) * lot;
  assert.equal(maxContracts(nvda(25), lot, LAUNCH), 23n); // 23.75 -> 23
  assert.equal(maxContracts(nvda(20), lot, LAUNCH), 19n); // 19.0
  assert.equal(maxContracts(nvda(2), lot, LAUNCH), 1n); // 1.9 -> 1
  assert.equal(maxContracts(nvda(1), lot, LAUNCH), 0n); // 0.95 -> 0
  assert.equal(maxContracts(nvda(100), lot, LAUNCH), 50n); // 95 -> cap
  assert.equal(maxContracts(nvda(100), 0n, LAUNCH), 0n); // a zero lot never divides
  // 100% utilisation writes every whole lot and no more.
  assert.equal(maxContracts(nvda(7) + 1n, lot, { ...LAUNCH, maxUtilizationBps: 10_000n }), 7n);
});

/*//////////////////////////////////////////////////////////////
                           THE PREMIUM FLOOR
//////////////////////////////////////////////////////////////*/

test('minUnitPrice6 is the ceiling of the per-contract floor', () => {
  // 218297934 * 40 / 10000 = 873191.736 -> 873192. Floor would be 873191.
  assert.equal(minUnitPrice6(SPOT, LAUNCH), 873_192n);
  assert.equal(ceilDiv(10n, 3n), 4n);
  assert.equal(ceilDiv(9n, 3n), 3n);
  assert.throws(() => ceilDiv(1n, 0n));
});

test('the ceiling clears Policy.checkPremium for every size; one unit below misses at n = 2', () => {
  // Policy.checkPremium: gross >= floor(spot * n * minPremiumBps / 10000), with gross = unit * n.
  const onChainMin = (n: bigint) => (SPOT * n * LAUNCH.minPremiumBps) / BPS;
  const ceilUnit = minUnitPrice6(SPOT, LAUNCH);
  const floorUnit = ceilUnit - 1n;

  for (let n = 1n; n <= 50n; n += 1n) {
    assert.ok(ceilUnit * n >= onChainMin(n), `ceiling unit clears the floor at n=${n}`);
  }
  // n = 1 happens to pass with the floored unit (873191 >= floor(873191.736) = 873191)...
  assert.ok(floorUnit * 1n >= onChainMin(1n));
  // ...and n = 2 is the first size where it reverts PremiumBelowMinimum: 1746382 < 1746383.
  assert.equal(floorUnit * 2n, 1_746_382n);
  assert.equal(onChainMin(2n), 1_746_383n);
  assert.ok(floorUnit * 2n < onChainMin(2n));
});

test('pickWrite prices from the floor, lifts to a CLAMPED last fill, never below the listable minimum, never above the strike', async () => {
  const floor = await pick();
  assert.ok(floor.ok);
  assert.equal(floor.unitPrice6, 873_192n);
  assert.equal(floor.priceSource, 'policy-floor');
  assert.equal(floor.contracts, 23n);
  assert.equal(floor.gross6, 873_192n * 23n);
  assert.equal(floor.toVault6 + floor.toOvercall6, floor.gross6);
  assert.equal(floor.endTime, CYCLE.exerciseTimestamp, 'the order ends at book close, not expiry');

  // A last fill within LAST_FILL_MAX_LIFT of the floor sets the ask.
  const lifted = await pick({ readLastFill: async () => 2_000_000n });
  assert.ok(lifted.ok);
  assert.equal(lifted.unitPrice6, 2_000_000n);
  assert.equal(lifted.priceSource, 'last-fill');

  // A last fill BEYOND the cap is clamped to 3x the floor, not obeyed: anyone can self-fill
  // one contract at an absurd price for the cost of the 5% fee, and an unclamped lift would
  // price the whole vault at the attacker's number and guarantee an unfilled week.
  assert.equal(LAST_FILL_MAX_LIFT, 3n);
  const capped = await pick({ readLastFill: async () => 4_000_000n });
  assert.ok(capped.ok);
  assert.equal(capped.unitPrice6, 873_192n * 3n);
  assert.equal(capped.priceSource, 'last-fill');
  const absurd = await pick({ readLastFill: async () => 300_000_000n });
  assert.ok(absurd.ok, 'clamped, not refused: 300 USDG on a 218 USDG spot is a fake print, not a price');
  assert.equal(absurd.unitPrice6, 873_192n * 3n);

  // A last fill below the floor is ignored: the floor is a floor.
  const low = await pick({ readLastFill: async () => 500_000n });
  assert.ok(low.ok);
  assert.equal(low.unitPrice6, 873_192n);
  assert.equal(low.priceSource, 'policy-floor');

  // A microscopic spot puts the floor under 20 base units; the ask is lifted to 20 so
  // Overcall's 5% does not round to a zero-amount consideration item.
  const tiny = await pick({
    spotUsdg6: 1_000n,
    rungs: rungs({ 0: { strikeUsdg6: 1_050n } }), // 5% OTM at a $0.001 spot
  });
  assert.ok(tiny.ok);
  assert.equal(tiny.unitPrice6, MIN_LISTABLE_UNIT_PRICE_6);
  assert.equal(MIN_LISTABLE_UNIT_PRICE_6, 20n);

  // An ask above the strike is a fat finger the vault would reject: refused, not clamped.
  // (Reachable today only through the manual override — the last-fill cap keeps the book's
  // signal far under any in-band strike at the launch policy.)
  const tooHigh = await pick({ unitPriceOverride6: 226_000_001n });
  assert.equal(tooHigh.ok, false);
  if (!tooHigh.ok) assert.equal(tooHigh.reason, 'premium-above-strike');
});

test('pickWrite asks the chosen rung first and only then the whole live ladder', async () => {
  const calls: bigint[][] = [];
  const result = await pick({
    readLastFill: async (ids) => {
      calls.push([...ids]);
      return calls.length === 1 ? null : 2_000_000n;
    },
  });
  assert.ok(result.ok);
  assert.deepEqual(calls[0], [LADDER[0]?.[0]]);
  assert.deepEqual(calls[1], LADDER.map(([id]) => id));
  assert.equal(result.unitPrice6, 2_000_000n);
  assert.equal(result.priceSource, 'last-fill');
});

test('the manual override wins over both the floor and the last fill, and is still bounded', async () => {
  const manual = await pick({ readLastFill: async () => 4_000_000n, unitPriceOverride6: 2_500_000n });
  assert.ok(manual.ok);
  assert.equal(manual.unitPrice6, 2_500_000n);
  assert.equal(manual.priceSource, 'manual-override');

  const tooLow = await pick({ unitPriceOverride6: 5n });
  assert.ok(tooLow.ok);
  assert.equal(tooLow.unitPrice6, 20n, 'an override under the listable floor is lifted to it');

  const tooHigh = await pick({ unitPriceOverride6: 226_000_001n });
  assert.equal(tooHigh.ok, false);
  if (!tooHigh.ok) assert.equal(tooHigh.reason, 'premium-above-strike');
});

/*//////////////////////////////////////////////////////////////
                  THE PREMIUM MARGIN (PREMIUM_MARGIN_BPS)
//////////////////////////////////////////////////////////////*/

/** Policy.checkPremium's on-chain minimum for `n` contracts at `spot`. */
const onChainMinGross = (spot: bigint, n: bigint) => (spot * n * LAUNCH.minPremiumBps) / BPS;

test('withPremiumMargin: margin 0 is the identity, the margin rounds UP, a negative is refused', () => {
  for (const floor of [0n, 1n, 20n, 873_192n, 2_619_576n, 123_456_789n]) {
    assert.equal(withPremiumMargin(floor, 0), floor, `ceil(f * 10000 / 10000) = f at ${floor}`);
  }
  // 873192 * 10050 / 10000 = 877557.96 -> 877558. The floored 877557 is short of +0.5%.
  assert.equal(withPremiumMargin(873_192n, 50), 877_558n);
  assert.ok(877_557n * BPS < 873_192n * 10_050n, 'rounding down would miss the margin');
  assert.equal(withPremiumMargin(1_000_000n, 50), 1_005_000n, 'an exact multiple does not round');
  assert.equal(withPremiumMargin(1n, 1), 2n, 'ceil(1.0001) = 2');
  assert.equal(withPremiumMargin(873_192n, 1000), 960_512n, 'the 10% cap: 960511.2 -> 960512');
  assert.equal(withPremiumMargin(873_192n, 50n), 877_558n, 'bigint and number margins agree');
  assert.throws(() => withPremiumMargin(873_192n, -1), /must not be negative/);
});

test('liftedUnitPrice6 at margin 0 is exactly the old inline max(floor, clamped last fill)', () => {
  const old = (floor: bigint, lastFill: bigint | null) =>
    lastFill !== null && floor > 0n && lastFill > floor
      ? lastFill < floor * LAST_FILL_MAX_LIFT
        ? lastFill
        : floor * LAST_FILL_MAX_LIFT
      : floor;
  for (const floor of [0n, 1n, 20n, 873_192n]) {
    const fills = [null, 0n, floor - 1n, floor, floor + 1n, 2n * floor, 3n * floor, 3n * floor + 1n, 300_000_000n];
    for (const lastFill of fills) {
      const got = liftedUnitPrice6(floor, 0, lastFill);
      assert.equal(got.unitPrice6, old(floor, lastFill), `floor ${floor}, last fill ${lastFill}`);
      assert.equal(got.lifted, lastFill !== null && floor > 0n && lastFill > floor, 'lifted exactly when the old code set last-fill');
    }
  }
});

test('pickWrite at margin 0 reproduces every existing price exactly', async () => {
  const cases: Array<[Partial<Parameters<typeof pickWrite>[0]>, bigint, string]> = [
    [{}, 873_192n, 'policy-floor'],
    [{ readLastFill: async () => 2_000_000n }, 2_000_000n, 'last-fill'],
    [{ readLastFill: async () => 4_000_000n }, 873_192n * 3n, 'last-fill'],
    [{ readLastFill: async () => 500_000n }, 873_192n, 'policy-floor'],
    [{ unitPriceOverride6: 2_500_000n }, 2_500_000n, 'manual-override'],
    [{ spotUsdg6: 1_000n, rungs: rungs({ 0: { strikeUsdg6: 1_050n } }) }, MIN_LISTABLE_UNIT_PRICE_6, 'policy-floor'],
  ];
  for (const [overrides, price, source] of cases) {
    const explicit = await pick({ ...overrides, premiumMarginBps: 0 });
    const fromEnv = await pick(overrides);
    assert.ok(explicit.ok && fromEnv.ok);
    assert.equal(explicit.unitPrice6, price);
    assert.equal(explicit.priceSource, source);
    assert.deepEqual(explicit, fromEnv, 'the default PREMIUM_MARGIN_BPS is 0: same plan, field for field');
  }
});

test('pickWrite at margin 50: at least +0.5%, survives a +0.5% spot tick, and the fee still splits per contract', async () => {
  const atFloor = await pick({ premiumMarginBps: 0 });
  const margined = await pick({ premiumMarginBps: 50 });
  assert.ok(atFloor.ok && margined.ok);
  assert.equal(margined.unitPrice6, 877_558n);
  assert.equal(margined.priceSource, 'policy-floor', 'the margin is part of the floor price, not a lift');
  assert.ok(margined.unitPrice6 * BPS >= atFloor.unitPrice6 * 10_050n, 'raised by >= 0.5%');

  // The revert the margin exists for. Spot ticks up 0.5% between the keeper's read and the
  // vault's approveListing: 218297934 -> 219389423. At the floor, 23 contracts miss the new
  // minimum; with the margin they clear it, at every size the sizer can produce.
  const ticked = (SPOT * 10_050n) / BPS;
  assert.equal(ticked, 219_389_423n);
  assert.ok(atFloor.unitPrice6 * 23n < onChainMinGross(ticked, 23n), 'margin 0: PremiumBelowMinimum on the uptick');
  for (let n = 1n; n <= LAUNCH.maxContractsCap; n += 1n) {
    assert.ok(margined.unitPrice6 * n >= onChainMinGross(ticked, n), `margin 50 clears the ticked floor at n=${n}`);
  }

  // Overcall's 5% is rounded per contract on the MARGINED unit: floor(877558 * 5%) = 43877.
  assert.equal(margined.contracts, 23n);
  assert.equal(margined.toOvercall6, 43_877n * 23n);
  assert.equal(margined.toVault6, (877_558n - 43_877n) * 23n);
  assert.equal(margined.toVault6 % margined.contracts, 0n);
  assert.equal(margined.toOvercall6 % margined.contracts, 0n);
  assert.equal(margined.gross6, margined.unitPrice6 * margined.contracts);

  // A last fill between the floor and the margined floor does not pull the price back down.
  const between = await pick({ premiumMarginBps: 50, readLastFill: async () => 875_000n });
  assert.ok(between.ok);
  assert.equal(between.unitPrice6, 877_558n);
  assert.equal(between.priceSource, 'policy-floor');
  // Above it, the last fill wins as before...
  const lifted = await pick({ premiumMarginBps: 50, readLastFill: async () => 2_000_000n });
  assert.ok(lifted.ok);
  assert.equal(lifted.unitPrice6, 2_000_000n);
  assert.equal(lifted.priceSource, 'last-fill');
  // ...and the 3x clamp stays anchored to the POLICY floor, so the margin does not widen what a
  // self-filled print can buy.
  const clamped = await pick({ premiumMarginBps: 50, readLastFill: async () => 300_000_000n });
  assert.ok(clamped.ok);
  assert.equal(clamped.unitPrice6, 873_192n * LAST_FILL_MAX_LIFT);
  // The manual override is an absolute price; the margin does not touch it.
  const manual = await pick({ premiumMarginBps: 50, unitPriceOverride6: 2_500_000n });
  assert.ok(manual.ok);
  assert.equal(manual.unitPrice6, 2_500_000n);
});

test('relistUnitPrice6: max(previous ask, margined LIVE floor); margin 0 is the old rule', () => {
  // Margin 0: exactly `floor > previous ? floor : previous`, and a failed read keeps previous.
  assert.equal(relistUnitPrice6(900_000n, 873_192n, 0), 900_000n);
  assert.equal(relistUnitPrice6(800_000n, 873_192n, 0), 873_192n);
  assert.equal(relistUnitPrice6(873_192n, 873_192n, 0), 873_192n);
  assert.equal(relistUnitPrice6(900_000n, null, 0), 900_000n);
  assert.equal(relistUnitPrice6(900_000n, null, 50), 900_000n, 'no live floor: the previous price, margin or not');

  // Margin 50 at an unchanged spot: an ask that sat at the bare floor is relisted with the margin.
  assert.equal(relistUnitPrice6(873_192n, 873_192n, 50), 877_558n);
  assert.equal(relistUnitPrice6(880_000n, 873_192n, 50), 880_000n, 'a higher previous ask is kept');

  // After a +0.5% tick the live floor is ceil(219389423 * 40 / 10000) = 877558.
  const tickedFloor = minUnitPrice6(219_389_423n, LAUNCH);
  assert.equal(tickedFloor, 877_558n);
  assert.equal(relistUnitPrice6(873_192n, tickedFloor, 0), 877_558n);
  assert.equal(relistUnitPrice6(877_558n, tickedFloor, 50), 881_946n, 'ceil(877558 * 1.005) = ceil(881945.79)');
});

/*//////////////////////////////////////////////////////////////
                       THE FEE SPLIT, IN LOCKSTEP
//////////////////////////////////////////////////////////////*/

/** contracts/test/unit/SplitDiff.t.sol `_lcg`: unchecked 64-bit LCG. */
function lcg(s: bigint): bigint {
  return (s * 6364136223846793005n + 1442695040888963407n) % (1n << 64n);
}

test('splitPremium agrees with Policy.splitPremium on the SplitDiff.t.sol vectors', () => {
  let seed = 12345n;
  const vectors: Array<[bigint, bigint, bigint, bigint, bigint]> = [];
  for (let i = 0; i < 40; i += 1) {
    seed = lcg(seed);
    const u = 20n + (seed % 50_000_000n);
    seed = lcg(seed);
    const n = 1n + (seed % 50n);

    const split = splitPremium(u, n);
    // The properties SplitDiff.t.sol asserts, verbatim.
    assert.equal(split.toVault6 + split.toOvercall6, split.gross6, 'split is lossless');
    assert.equal(split.gross6, u * n, 'gross is unit x contracts');
    assert.equal(split.toVault6 % n, 0n, 'consideration[0] divides by the order size');
    assert.equal(split.toOvercall6 % n, 0n, 'consideration[1] divides by the order size');
    assert.equal(split.toOvercall6, ((u * 500n) / 10_000n) * n, 'fee floors per contract, then multiplies');
    vectors.push([u, n, split.toVault6, split.toOvercall6, split.gross6]);
  }

  // The first six and the last vector, pinned. If the generator on either side changes, the
  // two suites stop testing the same inputs and this is what says so.
  assert.deepEqual(vectors.slice(0, 6), [
    [18277608n, 24n, 416729472n, 21933120n, 438662592n],
    [42273082n, 28n, 1124463984n, 59182312n, 1183646296n],
    [27215324n, 26n, 672218508n, 35379916n, 707598424n],
    [21603278n, 32n, 656739680n, 34565216n, 691304896n],
    [22372240n, 28n, 595101584n, 31321136n, 626422720n],
    [27647906n, 38n, 998089418n, 52531010n, 1050620428n],
  ]);
  assert.deepEqual(vectors[39], [33589238n, 30n, 957293310n, 50383830n, 1007677140n]);
});

test('rounding the fee on the total is a different, unfillable order', () => {
  // unit 30, two contracts. Per contract: fee floor(1.5) = 1, so 2 in total and 58 to the
  // writer. On the total: floor(60 * 5%) = 3, which does not divide by 2 — Seaport's
  // PARTIAL_OPEN scaling then reverts InexactFraction on any half fill.
  const split = splitPremium(30n, 2n);
  assert.equal(split.feePerContract6, 1n);
  assert.equal(split.toOvercall6, 2n);
  assert.equal(split.toVault6, 58n);
  const onTheTotal = (split.gross6 * OVERCALL_FEE_BPS) / BPS;
  assert.equal(onTheTotal, 3n);
  assert.notEqual(onTheTotal % 2n, 0n);
});

test('splitPremium refuses an ask whose 5% rounds to zero, and refuses zero sizes', () => {
  assert.throws(() => splitPremium(19n, 1n), /below 20/);
  assert.equal(splitPremium(20n, 1n).feePerContract6, 1n);
  assert.throws(() => splitPremium(0n, 1n));
  assert.throws(() => splitPremium(1_000_000n, 0n));
});
