// GENERATED by scripts/gen-abis.mjs from ops/abis/v2/OrderBook.json and the error fragments of ops/abis/v2/V2Errors.json. Do not edit by hand.
// OrderBook: the on-chain order board for series units, write-on-fill asks included.
export const orderBookAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "clearinghouse_",
        "type": "address",
        "internalType": "contract IClearinghouse"
      },
      {
        "name": "authority_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "feeRecipient_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "fees",
        "type": "tuple",
        "internalType": "struct V2Types.FeeParams",
        "components": [
          {
            "name": "premiumFeeBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "resaleFeeBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "takerFeeFlat",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "takerFeeCapBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "makerRebateBps",
            "type": "uint16",
            "internalType": "uint16"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "authority",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "cancel",
    "inputs": [
      {
        "name": "orderIds",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "claimOwed",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "clearinghouse",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "discountModule",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "feeParams",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct V2Types.FeeParams",
        "components": [
          {
            "name": "premiumFeeBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "resaleFeeBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "takerFeeFlat",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "takerFeeCapBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "makerRebateBps",
            "type": "uint16",
            "internalType": "uint16"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "feeRecipient",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "fundingOf",
    "inputs": [
      {
        "name": "maker",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "allowed",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "on",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getOrders",
    "inputs": [
      {
        "name": "orderIds",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "outputs": [
      {
        "name": "orders",
        "type": "tuple[]",
        "internalType": "struct V2Types.Order[]",
        "components": [
          {
            "name": "maker",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "longId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "kind",
            "type": "uint8",
            "internalType": "enum V2Types.OrderKind"
          },
          {
            "name": "price",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "units",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "filled",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "validUntil",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "cancelled",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isConsumingScheduledOp",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes4",
        "internalType": "bytes4"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isDelegate",
    "inputs": [
      {
        "name": "maker",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "delegate",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "lastOrderId",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "makerOrderCount",
    "inputs": [
      {
        "name": "maker",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "makerRegistry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IMakerRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "onERC1155BatchReceived",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "",
        "type": "uint256[]",
        "internalType": "uint256[]"
      },
      {
        "name": "",
        "type": "uint256[]",
        "internalType": "uint256[]"
      },
      {
        "name": "",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes4",
        "internalType": "bytes4"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "onERC1155Received",
    "inputs": [
      {
        "name": "operator",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "from",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "value",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes4",
        "internalType": "bytes4"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "ordersOfMaker",
    "inputs": [
      {
        "name": "maker",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "cursor",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "limit",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "orderIds",
        "type": "uint256[]",
        "internalType": "uint256[]"
      },
      {
        "name": "nextCursor",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ordersOfSeries",
    "inputs": [
      {
        "name": "longId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "cursor",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "limit",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "orderIds",
        "type": "uint256[]",
        "internalType": "uint256[]"
      },
      {
        "name": "nextCursor",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owed",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingFeeParams",
    "inputs": [],
    "outputs": [
      {
        "name": "params",
        "type": "tuple",
        "internalType": "struct V2Types.FeeParams",
        "components": [
          {
            "name": "premiumFeeBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "resaleFeeBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "takerFeeFlat",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "takerFeeCapBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "makerRebateBps",
            "type": "uint16",
            "internalType": "uint16"
          }
        ]
      },
      {
        "name": "effectiveAt",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "place",
    "inputs": [
      {
        "name": "longId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "kind",
        "type": "uint8",
        "internalType": "enum V2Types.OrderKind"
      },
      {
        "name": "price",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "units",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "validUntil",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "outputs": [
      {
        "name": "orderId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "placeFor",
    "inputs": [
      {
        "name": "maker",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "longId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "kind",
        "type": "uint8",
        "internalType": "enum V2Types.OrderKind"
      },
      {
        "name": "price",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "units",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "validUntil",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "outputs": [
      {
        "name": "orderId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "prune",
    "inputs": [
      {
        "name": "orderIds",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "outputs": [
      {
        "name": "pruned",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "quoteTake",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct V2Types.TakeParams",
        "components": [
          {
            "name": "longId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "buying",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "orderIds",
            "type": "uint256[]",
            "internalType": "uint256[]"
          },
          {
            "name": "units",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "minUnits",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "limitPrice",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "writeToSell",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "recipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "deadline",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "maxTotalFee",
            "type": "uint128",
            "internalType": "uint128"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "unitsFilled",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "premium",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "takerFee",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "sellerFees",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "replace",
    "inputs": [
      {
        "name": "orderId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "newPrice",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "newUnits",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "newOrderId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "seriesOrderCount",
    "inputs": [
      {
        "name": "longId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setAuthority",
    "inputs": [
      {
        "name": "newAuthority",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDelegate",
    "inputs": [
      {
        "name": "delegate",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "approved",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDiscountModule",
    "inputs": [
      {
        "name": "module",
        "type": "address",
        "internalType": "contract IFeeDiscount"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setFeeParams",
    "inputs": [
      {
        "name": "fees",
        "type": "tuple",
        "internalType": "struct V2Types.FeeParams",
        "components": [
          {
            "name": "premiumFeeBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "resaleFeeBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "takerFeeFlat",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "takerFeeCapBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "makerRebateBps",
            "type": "uint16",
            "internalType": "uint16"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setFeeRecipient",
    "inputs": [
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setFunding",
    "inputs": [
      {
        "name": "on",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setFundingAllowed",
    "inputs": [
      {
        "name": "maker",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "allowed",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setMakerRegistry",
    "inputs": [
      {
        "name": "registry",
        "type": "address",
        "internalType": "contract IMakerRegistry"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setTradingPaused",
    "inputs": [
      {
        "name": "paused",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "supportsInterface",
    "inputs": [
      {
        "name": "interfaceId",
        "type": "bytes4",
        "internalType": "bytes4"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "take",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct V2Types.TakeParams",
        "components": [
          {
            "name": "longId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "buying",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "orderIds",
            "type": "uint256[]",
            "internalType": "uint256[]"
          },
          {
            "name": "units",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "minUnits",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "limitPrice",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "writeToSell",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "recipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "deadline",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "maxTotalFee",
            "type": "uint128",
            "internalType": "uint128"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "unitsFilled",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "premium",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "takerFee",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "tradingPaused",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "usdg",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IERC20"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "AuthorityUpdated",
    "inputs": [
      {
        "name": "authority",
        "type": "address",
        "internalType": "address",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DelegateSet",
    "inputs": [
      {
        "name": "maker",
        "type": "address",
        "internalType": "address",
        "indexed": true
      },
      {
        "name": "delegate",
        "type": "address",
        "internalType": "address",
        "indexed": true
      },
      {
        "name": "approved",
        "type": "bool",
        "internalType": "bool",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DiscountModuleSet",
    "inputs": [
      {
        "name": "module",
        "type": "address",
        "internalType": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FeeParamsScheduled",
    "inputs": [
      {
        "name": "params",
        "type": "tuple",
        "internalType": "struct V2Types.FeeParams",
        "components": [
          {
            "name": "premiumFeeBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "resaleFeeBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "takerFeeFlat",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "takerFeeCapBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "makerRebateBps",
            "type": "uint16",
            "internalType": "uint16"
          }
        ],
        "indexed": false
      },
      {
        "name": "effectiveAt",
        "type": "uint40",
        "internalType": "uint40",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FeeParamsSet",
    "inputs": [
      {
        "name": "params",
        "type": "tuple",
        "internalType": "struct V2Types.FeeParams",
        "components": [
          {
            "name": "premiumFeeBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "resaleFeeBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "takerFeeFlat",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "takerFeeCapBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "makerRebateBps",
            "type": "uint16",
            "internalType": "uint16"
          }
        ],
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FeeRecipientSet",
    "inputs": [
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Funded",
    "inputs": [
      {
        "name": "maker",
        "type": "address",
        "internalType": "address",
        "indexed": true
      },
      {
        "name": "asset",
        "type": "address",
        "internalType": "address",
        "indexed": true
      },
      {
        "name": "requested",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      },
      {
        "name": "delivered",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FundingAllowedSet",
    "inputs": [
      {
        "name": "maker",
        "type": "address",
        "internalType": "address",
        "indexed": true
      },
      {
        "name": "allowed",
        "type": "bool",
        "internalType": "bool",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FundingFailed",
    "inputs": [
      {
        "name": "maker",
        "type": "address",
        "internalType": "address",
        "indexed": true
      },
      {
        "name": "asset",
        "type": "address",
        "internalType": "address",
        "indexed": true
      },
      {
        "name": "requested",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FundingSet",
    "inputs": [
      {
        "name": "maker",
        "type": "address",
        "internalType": "address",
        "indexed": true
      },
      {
        "name": "on",
        "type": "bool",
        "internalType": "bool",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MakerRegistrySet",
    "inputs": [
      {
        "name": "registry",
        "type": "address",
        "internalType": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OrderCancelled",
    "inputs": [
      {
        "name": "orderId",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": true
      },
      {
        "name": "unitsRemaining",
        "type": "uint64",
        "internalType": "uint64",
        "indexed": false
      },
      {
        "name": "pruned",
        "type": "bool",
        "internalType": "bool",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OrderFilled",
    "inputs": [
      {
        "name": "orderId",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": true
      },
      {
        "name": "longId",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": true
      },
      {
        "name": "taker",
        "type": "address",
        "internalType": "address",
        "indexed": true
      },
      {
        "name": "maker",
        "type": "address",
        "internalType": "address",
        "indexed": false
      },
      {
        "name": "units",
        "type": "uint64",
        "internalType": "uint64",
        "indexed": false
      },
      {
        "name": "price",
        "type": "uint128",
        "internalType": "uint128",
        "indexed": false
      },
      {
        "name": "premium",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      },
      {
        "name": "sellerFee",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      },
      {
        "name": "makerRebate",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      },
      {
        "name": "primary",
        "type": "bool",
        "internalType": "bool",
        "indexed": false
      },
      {
        "name": "takerIsBuyer",
        "type": "bool",
        "internalType": "bool",
        "indexed": false
      },
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OrderPlaced",
    "inputs": [
      {
        "name": "orderId",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": true
      },
      {
        "name": "maker",
        "type": "address",
        "internalType": "address",
        "indexed": true
      },
      {
        "name": "longId",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": true
      },
      {
        "name": "kind",
        "type": "uint8",
        "internalType": "enum V2Types.OrderKind",
        "indexed": false
      },
      {
        "name": "price",
        "type": "uint128",
        "internalType": "uint128",
        "indexed": false
      },
      {
        "name": "units",
        "type": "uint64",
        "internalType": "uint64",
        "indexed": false
      },
      {
        "name": "validUntil",
        "type": "uint40",
        "internalType": "uint40",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwedClaimed",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address",
        "indexed": true
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Taken",
    "inputs": [
      {
        "name": "taker",
        "type": "address",
        "internalType": "address",
        "indexed": true
      },
      {
        "name": "longId",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": true
      },
      {
        "name": "buying",
        "type": "bool",
        "internalType": "bool",
        "indexed": false
      },
      {
        "name": "units",
        "type": "uint64",
        "internalType": "uint64",
        "indexed": false
      },
      {
        "name": "premium",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      },
      {
        "name": "takerFee",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "TradingPausedSet",
    "inputs": [
      {
        "name": "paused",
        "type": "bool",
        "internalType": "bool",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AccessManagedInvalidAuthority",
    "inputs": [
      {
        "name": "authority",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "AccessManagedRequiredDelay",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "delay",
        "type": "uint32",
        "internalType": "uint32"
      }
    ]
  },
  {
    "type": "error",
    "name": "AccessManagedUnauthorized",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "BadPrice",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadUnits",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BelowMinUnits",
    "inputs": [
      {
        "name": "filled",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "min",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "CeilingExceeded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DeadlinePassed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FeeAboveMax",
    "inputs": [
      {
        "name": "fee",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "max",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "NoSource",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotAuthorized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderNotLive",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "PastCutoff",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "TradingPaused",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownSeries",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnsupportedAsset",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AlreadyFinal",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AlreadySettled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadExpiry",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadStrike",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CapExceeded",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "cap",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "CooldownActive",
    "inputs": [
      {
        "name": "readyAt",
        "type": "uint40",
        "internalType": "uint40"
      }
    ]
  },
  {
    "type": "error",
    "name": "CreatePaused",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InTheMoney",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientCollateral",
    "inputs": [
      {
        "name": "have",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "need",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "MarketDisabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MintPaused",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotMinter",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotSettled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OutflowCapExceeded",
    "inputs": [
      {
        "name": "available",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "outflow",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "OutsideRegularSession",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PinMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ResolveOutOfBand",
    "inputs": [
      {
        "name": "lo",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "hi",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "RouteRejected",
    "inputs": [
      {
        "name": "reason",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "SeriesIdCollision",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SourceNotPinned",
    "inputs": [
      {
        "name": "source",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "reason",
        "type": "bytes4",
        "internalType": "bytes4"
      }
    ]
  },
  {
    "type": "error",
    "name": "StaleSpot",
    "inputs": [
      {
        "name": "updatedAt",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ThirdPartyRedeemDisabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TooEarly",
    "inputs": [
      {
        "name": "notBefore",
        "type": "uint40",
        "internalType": "uint40"
      }
    ]
  }
] as const;
