// Regenerate the typed ABI modules in abis/ from the shared ops/abis JSON artefacts.
//
// WHY THIS EXISTS: ponder (and abitype underneath it) infers event argument types from an ABI
// literal. `import x from "./Vault.json"` widens every `type` field to `string`, which
// destroys that inference and leaves every handler's `event.args` typed as `any`. So the JSON
// is transcribed once into an `as const` TypeScript module. ops/ stays the source of truth;
// run `pnpm gen:abis` after any ABI change there.
//
// The transcription is not a straight copy. ops/abis/StockToken.json interleaves `_comment`
// separators and annotates entries with `_selector` / `_verified`, which are useful to a human
// and fatal to abitype's `Abi` constraint, so every entry is reduced to the canonical keys.
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.resolve(here, "..");
const opsAbis = path.resolve(pkgRoot, "..", "ops", "abis");

const targets = [
  {
    src: "Vault.json",
    out: "vault.ts",
    export: "vaultAbi",
    note: "Callhouse Vault. Compiled artefact of contracts/src/Vault.sol.",
  },
  {
    src: "OvercallRegistry.json",
    out: "overcallRegistry.ts",
    export: "overcallRegistryAbi",
    note:
      "Overcall per-market registry. The NVDA registry on chain 4663 is\n// 0x8E973cE1A6884E28Ad3E377d5f670Bc0b463f4EA. NOTE: the cycle struct has NO status field —\n// `isWritingOpen()` and `isCycleLive()` are the whole state machine.",
  },
  {
    src: "ValoremClear.json",
    out: "valoremClear.ts",
    export: "valoremClearAbi",
    note:
      "ValoremOptionsClearinghouse, exact upstream build, 0x9a7b40e5c1dB1Af822ef091c990b58b02C78C0C0.\n// Claim.amountWritten / amountExercised are 1e18-scaled scalars, NOT contract counts; the\n// event arguments (OptionsWritten.amount, OptionsExercised.amount) are raw counts.",
  },
  {
    src: "StockToken.json",
    out: "stockToken.ts",
    export: "stockTokenAbi",
    note:
      "Robinhood Chain Stock Token: ERC-20 plus ERC-8056 scaled UI amount, recovered from the\n// deployed implementation's bytecode and verified live (see ops/abis/StockToken.json).\n// `uiMultiplier()` is DISPLAY ONLY — the vault never rebases and its share maths use raw\n// balances. `oraclePaused()` gates writes: a paused oracle blocks rollOpen.",
  },
];

const ITEM_KEYS = ["type", "name", "inputs", "outputs", "stateMutability", "anonymous"];
const PARAM_KEYS = ["name", "type", "internalType", "components", "indexed"];

const cleanParam = (p) => {
  const out = {};
  for (const k of PARAM_KEYS) {
    if (p[k] === undefined) continue;
    out[k] = k === "components" ? p[k].map(cleanParam) : p[k];
  }
  return out;
};

const cleanItem = (item) => {
  const out = {};
  for (const k of ITEM_KEYS) {
    if (item[k] === undefined) continue;
    out[k] = k === "inputs" || k === "outputs" ? item[k].map(cleanParam) : item[k];
  }
  return out;
};

const unwrap = (json) => (Array.isArray(json) ? json : (json.abi ?? json));

for (const t of targets) {
  const raw = JSON.parse(readFileSync(path.join(opsAbis, t.src), "utf8"));
  // Drop the `_comment` separators, then strip the annotation keys from what is left.
  const abi = unwrap(raw)
    .filter((item) => typeof item?.type === "string")
    .map(cleanItem);

  const body = `// GENERATED by scripts/gen-abis.mjs from ops/abis/${t.src}. Do not edit by hand.
// ${t.note}
export const ${t.export} = ${JSON.stringify(abi, null, 2)} as const;
`;
  writeFileSync(path.join(pkgRoot, "abis", t.out), body, "utf8");
  console.log(`wrote abis/${t.out} (${abi.length} entries)`);
}
