/*
 * ops/v2/post-broadcast-regen.test.mjs — the enumeration is the guard, so it is what gets broken here.
 *
 *   node --test ops/v2/post-broadcast-regen.test.mjs
 *
 * The pure half (`parseHeader`, `resolveGenerator`, `enumerate`) runs on synthetic trees: a file list,
 * a head reader and an existence oracle, no git and no process. The integration tests read the REAL
 * tree through git and pin the set of generators the registry write-back must reach; when a generator
 * is added or an output loses its header, one of them goes red by name.
 *
 * Each refusal in the runner has a test that PRODUCES it: a generated file naming an unknown
 * generator, one naming a generator that does not exist, a `*.generated.json` nobody names, and a
 * recipe with no output in the tree. A checker that cannot fail proves nothing.
 */
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import path from "node:path";
import { test } from "node:test";

import { CANONICAL_REGISTRY, RECIPES, REPO, enumerate, parseHeader, resolveGenerator } from "./post-broadcast-regen.mjs";

/* ---------------------------------------------------------------- headers, as the tree writes them */

test("parseHeader reads every header form the tree uses", () => {
  const cases = [
    ["// GENERATED by web/scripts/gen-markets.mjs from ops/markets/tier1.json — do not edit.", "web/scripts/gen-markets.mjs", "ops/markets/tier1.json"],
    ["// GENERATED by scripts/gen-abis.mjs from ops/abis/v2/HouseVault.json and the error fragments of ops/abis/v2/V2Errors.json. Do not edit by hand.", "scripts/gen-abis.mjs", "ops/abis/v2/HouseVault.json"],
    ["// GENERATED by indexer/scripts/gen-v2-registry.mjs from ops/markets/tier1.json.\n// second line", "indexer/scripts/gen-v2-registry.mjs", "ops/markets/tier1.json"],
    ["/** Generated by scripts/gen-reward-epochs.mjs; do not edit. */", "scripts/gen-reward-epochs.mjs", null],
    ["# ops/v2/env/cranker.env — keeper V2_MODE=cranker\n# GENERATED by ops/v2-env.mjs from ops/markets/tier1.json (v2 interface version 8). Do not edit by hand:", "ops/v2-env.mjs", "ops/markets/tier1.json"],
    ["<!-- GENERATED by ops/markets/render-docs.mjs in the app repository from ops/markets/tier1.json. -->", "ops/markets/render-docs.mjs", "ops/markets/tier1.json"],
    ["// GENERATED by `ops/v2/rehearse/5-report.mjs` from the run", "ops/v2/rehearse/5-report.mjs", null],
    // The input is the first path after `from` on the header line; the next line is not the header.
    ["// GENERATED by scripts/gen-abis.mjs. Do not edit by hand.\n// from ops/abis/v2/Other.json", "scripts/gen-abis.mjs", null],
  ];
  for (const [head, generator, from] of cases) {
    const h = parseHeader(head);
    assert.ok(h, `no header parsed from: ${head}`);
    assert.equal(h.generator, generator, head);
    assert.equal(h.from, from, head);
  }
  assert.equal(parseHeader("export const x = 1;\n// nothing generated here"), null);
  // A sentence that merely mentions generation is not a header: the word order is the convention.
  assert.equal(parseHeader("// these files are generated, by hand, from nothing"), null);
});

test("resolveGenerator: repository-relative first, then the output's package", () => {
  const files = new Set(["web/package.json", "web/scripts/gen-abis.mjs", "ops/v2-env.mjs"]);
  const exists = (p) => files.has(p);
  assert.equal(resolveGenerator("web/lib/abi/v2/houseVault.ts", "scripts/gen-abis.mjs", exists), "web/scripts/gen-abis.mjs");
  assert.equal(resolveGenerator("ops/v2/env/cranker.env", "ops/v2-env.mjs", exists), "ops/v2-env.mjs");
  // No package.json above ops/, and no such file at the root: unresolved, never guessed.
  assert.equal(resolveGenerator("ops/v2/env/cranker.env", "scripts/gen-abis.mjs", exists), null);
  // A package generator named from another package is not the same script.
  assert.equal(resolveGenerator("indexer/abis/v2/houseVault.ts", "scripts/gen-abis.mjs", exists), null);
});

/* ---------------------------------------------------------------- enumerate on synthetic trees */

/** A tiny tree: one package generator, one root generator, one header-less JSON, one plain source file. */
function tree(extra = {}) {
  const contents = {
    "web/package.json": "{}",
    "web/scripts/gen-abis.mjs": "// the generator",
    "web/lib/abi/v2/a.ts": "// GENERATED by scripts/gen-abis.mjs from ops/abis/v2/A.json. Do not edit by hand.",
    "web/lib/abi/v2/b.ts": "// GENERATED by scripts/gen-abis.mjs from ops/abis/v2/B.json. Do not edit by hand.",
    "web/scripts/gen-markets.mjs": "// the generator",
    "web/lib/markets.generated.ts": "// GENERATED by web/scripts/gen-markets.mjs from ops/markets/tier1.json — do not edit.",
    "indexer/scripts/gen-card-registry.mjs": "// writes cardRegistry.generated.json",
    "indexer/lib/v2/cardRegistry.generated.json": "{ \"projectionSha256\": \"…\" }",
    "web/lib/markets.ts": "export const MARKETS = [];",
    ...extra,
  };
  const files = Object.keys(contents).filter((f) => contents[f] !== null);
  return { files, readHead: (f) => contents[f] ?? null, exists: (p) => files.includes(p) };
}

const RECIPES_SMALL = {
  "web/scripts/gen-abis.mjs": { input: "ops/abis/v2", cwd: "web", write: ["node", "scripts/gen-abis.mjs"], check: ["node", "scripts/gen-abis.mjs", "--check"] },
  "web/scripts/gen-markets.mjs": { input: "registry", cwd: ".", write: ["node", "x"], check: ["node", "x", "--check"], registryFlag: true },
  "indexer/scripts/gen-card-registry.mjs": { input: "registry", cwd: ".", write: ["node", "x"], check: ["node", "x", "--check"], registryFlag: true, headerless: ["indexer/lib/v2/cardRegistry.generated.json"] },
};

test("enumerate attributes every generated file, by header or by recipe, and refuses nothing on a clean tree", () => {
  const t = tree();
  const r = enumerate(t.files, t.readHead, t.exists, RECIPES_SMALL);
  assert.deepEqual(r.refusals, []);
  assert.deepEqual(r.recipes["web/scripts/gen-abis.mjs"].outputs.map((o) => o.file).sort(), ["web/lib/abi/v2/a.ts", "web/lib/abi/v2/b.ts"]);
  assert.deepEqual(r.recipes["web/scripts/gen-abis.mjs"].outputs.map((o) => o.from), ["ops/abis/v2/A.json", "ops/abis/v2/B.json"]);
  assert.deepEqual(r.recipes["web/scripts/gen-markets.mjs"].outputs, [{ file: "web/lib/markets.generated.ts", from: "ops/markets/tier1.json" }]);
  assert.deepEqual(r.recipes["indexer/scripts/gen-card-registry.mjs"].outputs, [{ file: "indexer/lib/v2/cardRegistry.generated.json", from: null }]);
  // A generator's own source mentions the convention in its doc comment; it is not its own output.
  assert.ok(!Object.values(r.recipes).some((x) => x.outputs.some((o) => o.file.endsWith("gen-abis.mjs"))));
});

test("REFUSAL: a generated file naming a generator with no recipe", () => {
  const t = tree({
    "site/scripts/gen-pages.mjs": "// a new generator nobody taught the runner",
    "site/pages.generated.ts": "// GENERATED by site/scripts/gen-pages.mjs from ops/markets/tier1.json",
  });
  const r = enumerate(t.files, t.readHead, t.exists, RECIPES_SMALL);
  assert.equal(r.refusals.length, 1, r.refusals.join("; "));
  assert.match(r.refusals[0], /^site\/pages\.generated\.ts: generated by 'site\/scripts\/gen-pages\.mjs', which has no recipe here/);
});

test("REFUSAL: a header naming a generator that does not exist at the root or in the package", () => {
  const t = tree({ "web/lib/abi/v2/c.ts": "// GENERATED by scripts/gen-abis-v9.mjs from ops/abis/v2/C.json." });
  const r = enumerate(t.files, t.readHead, t.exists, RECIPES_SMALL);
  assert.equal(r.refusals.length, 1, r.refusals.join("; "));
  assert.match(r.refusals[0], /^web\/lib\/abi\/v2\/c\.ts: header names generator 'scripts\/gen-abis-v9\.mjs', which exists neither/);
});

test("REFUSAL: a *.generated.json with no header that no recipe names", () => {
  const t = tree({ "indexer/lib/v2/orphan.generated.json": "{}" });
  const r = enumerate(t.files, t.readHead, t.exists, RECIPES_SMALL);
  assert.equal(r.refusals.length, 1, r.refusals.join("; "));
  assert.match(r.refusals[0], /^indexer\/lib\/v2\/orphan\.generated\.json: a \*\.generated\.\* file with no 'GENERATED by' header and no recipe/);
});

test("REFUSAL: a recipe whose outputs vanished from the tree (stale table), and one whose script is gone", () => {
  const t = tree({ "web/lib/markets.generated.ts": null });
  const r = enumerate(t.files, t.readHead, t.exists, RECIPES_SMALL);
  assert.ok(r.refusals.some((x) => x.startsWith("recipe 'web/scripts/gen-markets.mjs' has no discovered output")), r.refusals.join("; "));
  const t2 = tree({ "web/scripts/gen-markets.mjs": null });
  const r2 = enumerate(t2.files, t2.readHead, t2.exists, RECIPES_SMALL);
  assert.ok(r2.refusals.some((x) => x === "recipe 'web/scripts/gen-markets.mjs' names a generator that does not exist"), r2.refusals.join("; "));
});

test("skip recipes are listed with their reason and never refused for having no output", () => {
  const t = tree();
  const recipes = { ...RECIPES_SMALL, "ops/recon/probe.mjs": { skip: "one-shot" } };
  const r = enumerate(t.files, t.readHead, t.exists, recipes);
  assert.deepEqual(r.refusals, []);
  assert.deepEqual(r.excluded.map((e) => [e.generator, e.reason]), [["ops/recon/probe.mjs", "one-shot"]]);
  assert.ok(!("ops/recon/probe.mjs" in r.recipes));
});

/* ---------------------------------------------------------------- the real tree */

function realTree() {
  const files = execFileSync("git", ["ls-files", "-z"], { cwd: REPO, encoding: "utf8" }).split("\0").filter(Boolean);
  const readHead = (f) => {
    try { return readFileSync(path.join(REPO, f)).subarray(0, 1200).toString("utf8"); } catch { return null; }
  };
  const exists = (p) => files.includes(p);
  return { files, readHead, exists };
}

test("the real tree enumerates with zero refusals", () => {
  const t = realTree();
  const r = enumerate(t.files, t.readHead, t.exists);
  assert.deepEqual(r.refusals, []);
});

test("the real tree: every projection of the registry has a recipe that takes --registry, and the set is the one the write-back must reach", () => {
  const t = realTree();
  const { recipes } = enumerate(t.files, t.readHead, t.exists);
  // Every tracked file whose header says it comes from ops/markets/tier1.json belongs to a recipe that
  // can be pointed at the written-back file. A new registry consumer without --registry support would
  // fail here first.
  const fromRegistry = Object.values(recipes).filter((r) => r.outputs.some((o) => o.from === "ops/markets/tier1.json"));
  assert.ok(fromRegistry.length >= 4, `expected the registry projections, saw ${fromRegistry.map((r) => r.generator).join(", ")}`);
  for (const r of fromRegistry) {
    if (r.role === "registry") continue; // the builder writes tier1.json itself
    assert.equal(r.registryFlag, true, `${r.generator} renders from tier1.json but its recipe has no --registry`);
    assert.equal(r.input, "registry", `${r.generator} renders from tier1.json but its recipe says input '${r.input}'`);
  }
  const pinned = ["web/scripts/gen-markets.mjs", "indexer/scripts/gen-v2-registry.mjs", "indexer/scripts/gen-card-registry.mjs", "ops/v2-env.mjs", "ops/keeper-env.sh"];
  for (const g of pinned) assert.ok(g in recipes && recipes[g].outputs.length > 0, `${g} missing or without outputs`);
  // render-docs writes outside the repository; its recipe exists, is external, and is skipped on a rehearsal file.
  assert.equal(recipes["ops/markets/render-docs.mjs"].external, true);
  assert.equal(recipes["ops/markets/render-docs.mjs"].registryFlag, false);
  // The three package ABI renderers resolve from `scripts/gen-abis.mjs` to their own package.
  for (const pkg of ["web", "indexer", "keeper"]) assert.ok(recipes[`${pkg}/scripts/gen-abis.mjs`].outputs.length >= 20, `${pkg} gen-abis outputs`);
});

test("every recipe names a script that exists, every write/check argv starts with a runnable, and placeholders are known", () => {
  for (const [gen, r] of Object.entries(RECIPES)) {
    assert.ok(t0(gen), `${gen} does not exist`);
    if (r.skip) continue;
    for (const argv of [r.write, r.check, r.checkOnly].filter(Boolean)) {
      assert.ok(["node", gen].includes(argv[0]) || argv[0].endsWith(".sh"), `${gen}: argv[0] '${argv[0]}'`);
      for (const a of argv) for (const m of a.matchAll(/\{(\w+)\}/g)) assert.ok(["registry", "docsOut", "docsSibling"].includes(m[1]), `${gen}: unknown placeholder {${m[1]}}`);
      if (argv.some((a) => a.includes("{registry}"))) assert.equal(r.registryFlag, true, `${gen} uses {registry} but registryFlag is not true`);
    }
    assert.ok(t0(path.posix.join(r.cwd, ".")), `${gen}: cwd ${r.cwd}`);
  }
  assert.equal(path.basename(CANONICAL_REGISTRY), "tier1.json");
});

function t0(rel) {
  try { readFileSync(path.join(REPO, rel)); return true; } catch (e) { return e.code === "EISDIR"; }
}
