// GENERATED by indexer/scripts/gen-v2-registry.mjs from ops/markets/tier1.json.
// The production image contains indexer/ only; regenerate after any registry change.
export const V2_REGISTRY = {
  "chainId": 4663,
  "interfaceVersion": 8,
  "deployBlock": null,
  "contracts": {
    "clearinghouse": null,
    "orderBook": null,
    "settlementOracle": null,
    "expiryCalendar": null,
    "keeperRewards": null,
    "autoRoller": null,
    "payoutAdapter": null,
    "makerVault": null,
    "makerRegistry": null,
    "rewardsDistributor": null,
    "accessManager": null,
    "houseVault": null,
    "houseVaultFactory": null,
    "hedger": null,
    "rewardsDistributorLender": null,
    "earnVault": null,
    "stockVenueAdapter": null,
    "sources": {
      "chainlink": null,
      "univ3": null,
      "dataStreams": null
    }
  },
  "safes": {
    "admin": "0x6f8A7B77b72511cD8939596b1659bA28C28f101B",
    "treasury": "0x014b996a084690FB27265BfAC157b04e9FeBbF4E"
  },
  "flywheel": {
    "feeSplitter": null,
    "buybackExecutor": null,
    "deployBlock": null
  },
  "fees": {
    "premiumFeeBps": 500,
    "mintFeePpm": 0,
    "allowRent": false,
    "resaleFeeBps": 0,
    "takerFeeFlat": "100000",
    "takerFeeCapBps": 1000,
    "makerRebateBps": 5000,
    "exerciseFeeBps": 25
  },
  "defaults": {
    "ladder": {
      "weekly": {
        "rungs": 5,
        "firstOtmBps": 200,
        "stepBps": 200,
        "cardTargetBps": 400
      },
      "daily": {
        "rungs": 5,
        "firstOtmBps": 100,
        "stepBps": 100,
        "cardTargetBps": 200
      }
    },
    "expiriesAhead": {
      "daily": 3,
      "weekly": 2
    }
  },
  "launchSet": {
    "note": "The v8 launch set, owner ruling 2026-09-21: launch is NVDA and SPCX only. This is the AUTHORITATIVE list and it is deliberately NOT derived from `wave` or `status`. Waves mean rollout ORDER and no market moves bucket for this; the two fields answer different questions and a tool that infers the launch set from either gets a different answer. `markets` names tickers that must exist in `markets[]`; build-markets.mjs validates that and preserves this block across a rebuild.",
    "markets": [
      "NVDA",
      "SPCX"
    ]
  },
  "markets": [
    {
      "ticker": "AAPL",
      "name": "Apple • Robinhood Token",
      "underlying": "0xaF3D76f1834A1d425780943C99Ea8A608f8a93f9",
      "uiMultiplier": "1000566080061092436",
      "status": "planned",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": {
        "venue": "v4",
        "fee": 3000,
        "tickSpacing": 60,
        "poolId": "0xc748f4671a867db48b552f6b7650bf3255e05f80f00e3f7aad1b17ccb7898fdb"
      },
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 3600,
        "route": {
          "venue": "v4",
          "fee": 3000,
          "tickSpacing": 60,
          "poolId": "0xc748f4671a867db48b552f6b7650bf3255e05f80f00e3f7aad1b17ccb7898fdb"
        }
      },
      "overrides": {}
    },
    {
      "ticker": "AMD",
      "name": "AMD • Robinhood Token",
      "underlying": "0x86923f96303D656E4aa86D9d42D1e57ad2023fdC",
      "uiMultiplier": "1000000000000000000",
      "status": "planned",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": null,
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 3600,
        "route": null
      },
      "overrides": {}
    },
    {
      "ticker": "AMZN",
      "name": "Amazon • Robinhood Token",
      "underlying": "0x12f190a9F9d7D37a250758b26824B97CE941bF54",
      "uiMultiplier": "1000000000000000000",
      "status": "planned",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": null,
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 3600,
        "route": null
      },
      "overrides": {}
    },
    {
      "ticker": "ASML",
      "name": "ASML Holding NV • Robinhood Token",
      "underlying": "0x47F93d52cBeC7C6D2CfC080e154002370a60dAEA",
      "uiMultiplier": "1000101323251417769",
      "status": "planned",
      "strikeTick": "10000000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": null,
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 21600,
        "route": null
      },
      "overrides": {}
    },
    {
      "ticker": "BABA",
      "name": "Alibaba • Robinhood Token",
      "underlying": "0xad25Ac6C84D497db898fa1E8387bf6Af3532a1c4",
      "uiMultiplier": "1000000000000000000",
      "status": "planned",
      "strikeTick": "1000000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": null,
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 21600,
        "route": null
      },
      "overrides": {}
    },
    {
      "ticker": "CLSK",
      "name": "CleanSpark • Robinhood Token",
      "underlying": "0xcBB95BBF36099d34dA091dc6Fa6F49EfA257Cee3",
      "uiMultiplier": "1000000000000000000",
      "status": "planned",
      "strikeTick": "500000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": null,
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 21600,
        "route": null
      },
      "overrides": {}
    },
    {
      "ticker": "COIN",
      "name": "Coinbase • Robinhood Token",
      "underlying": "0x6330D8C3178a418788dF01a47479c0ce7CCF450b",
      "uiMultiplier": "1000000000000000000",
      "status": "planned",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": null,
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 21600,
        "route": null
      },
      "overrides": {}
    },
    {
      "ticker": "CRCL",
      "name": "Circle Internet Group • Robinhood Token",
      "underlying": "0xdF0992E440dD0be65BD8439b609d6D4366bf1CB5",
      "uiMultiplier": "1000000000000000000",
      "status": "planned",
      "strikeTick": "1000000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": null,
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 21600,
        "route": null
      },
      "overrides": {}
    },
    {
      "ticker": "CRWV",
      "name": "CoreWeave • Robinhood Token",
      "underlying": "0x5f10A1C971B69e47e059e1dC91901B59b3fB49C3",
      "uiMultiplier": "1000000000000000000",
      "status": "planned",
      "strikeTick": "1000000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": null,
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 3600,
        "route": null
      },
      "overrides": {}
    },
    {
      "ticker": "DELL",
      "name": "Dell • Robinhood Token",
      "underlying": "0x941AE714EC6D8130c7B75d67160Ca08f1e7d11Dd",
      "uiMultiplier": "1000063708620124549",
      "status": "planned",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": {
        "venue": "v4",
        "fee": 5000,
        "tickSpacing": 25,
        "poolId": "0x729651c09684919bdffda473141be4e908ee0e8cf8a43f41135831217fa7d3bb"
      },
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 3600,
        "route": {
          "venue": "v4",
          "fee": 5000,
          "tickSpacing": 25,
          "poolId": "0x729651c09684919bdffda473141be4e908ee0e8cf8a43f41135831217fa7d3bb"
        }
      },
      "overrides": {}
    },
    {
      "ticker": "EWY",
      "name": "iShares MSCI South Korea fund • Robinhood Token",
      "underlying": "0x7f0aBeF0C07280F82c6a08ead09dEd6BAE2C13Fc",
      "uiMultiplier": "1000000000000000000",
      "status": "planned",
      "strikeTick": "1000000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": null,
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 21600,
        "route": null
      },
      "overrides": {}
    },
    {
      "ticker": "GME",
      "name": "GameStop • Robinhood Token",
      "underlying": "0x1b0E319c6A659F002271B69dB8A7df2F911c153E",
      "uiMultiplier": "1000000000000000000",
      "status": "planned",
      "strikeTick": "500000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": null,
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 21600,
        "route": null
      },
      "overrides": {}
    },
    {
      "ticker": "GOOGL",
      "name": "Alphabet Class A • Robinhood Token",
      "underlying": "0x2e0847E8910a9732eB3fb1bb4b70a580ADAD4FE3",
      "uiMultiplier": "1000193924414112587",
      "status": "planned",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": {
        "venue": "v4",
        "fee": 300,
        "tickSpacing": 3,
        "poolId": "0x43fe16b75cabbf38f5b185d16142b02d1d9200d8f1ba17cb6cf899f562c6197f"
      },
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 3600,
        "route": {
          "venue": "v4",
          "fee": 300,
          "tickSpacing": 3,
          "poolId": "0x43fe16b75cabbf38f5b185d16142b02d1d9200d8f1ba17cb6cf899f562c6197f"
        }
      },
      "overrides": {}
    },
    {
      "ticker": "INTC",
      "name": "Intel • Robinhood Token",
      "underlying": "0xc72b96e0E48ecd4DC75E1e45396e26300BC39681",
      "uiMultiplier": "1000000000000000000",
      "status": "planned",
      "strikeTick": "500000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": {
        "venue": "v4",
        "fee": 10000,
        "tickSpacing": 200,
        "poolId": "0xf2e329e631d0fb315a5c563ee3a9120f24822b5ef6c502a91cb56b174d5d8c22"
      },
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 3600,
        "route": {
          "venue": "v4",
          "fee": 10000,
          "tickSpacing": 200,
          "poolId": "0xf2e329e631d0fb315a5c563ee3a9120f24822b5ef6c502a91cb56b174d5d8c22"
        }
      },
      "overrides": {}
    },
    {
      "ticker": "IONQ",
      "name": "IonQ • Robinhood Token",
      "underlying": "0x558378E000D634A36593E338eBacdd6207640EfE",
      "uiMultiplier": "1000000000000000000",
      "status": "planned",
      "strikeTick": "500000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": null,
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 21600,
        "route": null
      },
      "overrides": {}
    },
    {
      "ticker": "META",
      "name": "Meta Platforms • Robinhood Token",
      "underlying": "0xc0D6457C16Cc70d6790Dd43521C899C87ce02f35",
      "uiMultiplier": "1000000000000000000",
      "status": "planned",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": {
        "venue": "v4",
        "fee": 3000,
        "tickSpacing": 60,
        "poolId": "0x5875d407a42965b0e768c8925cea290e06fa50603ef34fc99eb92a1050e6ae36"
      },
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 3600,
        "route": {
          "venue": "v4",
          "fee": 3000,
          "tickSpacing": 60,
          "poolId": "0x5875d407a42965b0e768c8925cea290e06fa50603ef34fc99eb92a1050e6ae36"
        }
      },
      "overrides": {}
    },
    {
      "ticker": "MSFT",
      "name": "Microsoft • Robinhood Token",
      "underlying": "0xe93237C50D904957Cf27E7B1133b510C669c2e74",
      "uiMultiplier": "1000412952576205964",
      "status": "planned",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": {
        "venue": "v4",
        "fee": 3000,
        "tickSpacing": 60,
        "poolId": "0x9194a557b6a6bb2236b49ea7e2bbccec5d3eeb705aef00903be4b3de1d949579"
      },
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 3600,
        "route": {
          "venue": "v4",
          "fee": 3000,
          "tickSpacing": 60,
          "poolId": "0x9194a557b6a6bb2236b49ea7e2bbccec5d3eeb705aef00903be4b3de1d949579"
        }
      },
      "overrides": {}
    },
    {
      "ticker": "MSTR",
      "name": "Strategy Inc. • Robinhood Token",
      "underlying": "0xec262a75e413fAfD0dF80480274532C79D42da09",
      "uiMultiplier": "1000000000000000000",
      "status": "planned",
      "strikeTick": "1000000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": {
        "venue": "v4",
        "fee": 2500,
        "tickSpacing": 25,
        "poolId": "0x319bac87e616a89e241c10aeb8afd4892a852cdd8b373cd9765ecddc40b87cfe"
      },
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 3600,
        "route": {
          "venue": "v4",
          "fee": 2500,
          "tickSpacing": 25,
          "poolId": "0x319bac87e616a89e241c10aeb8afd4892a852cdd8b373cd9765ecddc40b87cfe"
        }
      },
      "overrides": {}
    },
    {
      "ticker": "MU",
      "name": "Micron Technology • Robinhood Token",
      "underlying": "0xfF080c8ce2E5feadaCa0Da81314Ae59D232d4afD",
      "uiMultiplier": "1000074823219171086",
      "status": "planned",
      "strikeTick": "5000000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": null,
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 3600,
        "route": null
      },
      "overrides": {}
    },
    {
      "ticker": "NBIS",
      "name": "Nebius Group • Robinhood Token",
      "underlying": "0x9D9c6684F596F66a64C030B93A886D51Fd4D7931",
      "uiMultiplier": "1000000000000000000",
      "status": "planned",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": null,
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 21600,
        "route": null
      },
      "overrides": {}
    },
    {
      "ticker": "NVDA",
      "name": "NVIDIA • Robinhood Token",
      "underlying": "0xd0601CE157Db5bdC3162BbaC2a2C8aF5320D9EEC",
      "uiMultiplier": "1000775159164630595",
      "status": "planned",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": {
        "venue": "v4",
        "fee": 375,
        "tickSpacing": 4,
        "poolId": "0xdf5c0bcd967d54774c139a4ef803ec994779736346fb4c21b50ed241b1fd2682"
      },
      "settlement": {
        "sourceCount": 2,
        "uncorroboratedDelayS": 21600,
        "route": {
          "venue": "v4",
          "fee": 375,
          "tickSpacing": 4,
          "poolId": "0xdf5c0bcd967d54774c139a4ef803ec994779736346fb4c21b50ed241b1fd2682"
        }
      },
      "overrides": {}
    },
    {
      "ticker": "ORCL",
      "name": "Oracle • Robinhood Token",
      "underlying": "0xb0992820E760d836549ba69BC7598b4af75dEE03",
      "uiMultiplier": "1002210914971013375",
      "status": "planned",
      "strikeTick": "1000000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": null,
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 3600,
        "route": null
      },
      "overrides": {}
    },
    {
      "ticker": "PLTR",
      "name": "Palantir Technologies • Robinhood Token",
      "underlying": "0x894E1EC2D74FFE5AEF8Dc8A9e84686acCB964F2A",
      "uiMultiplier": "1000000000000000000",
      "status": "planned",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": {
        "venue": "v4",
        "fee": 1500,
        "tickSpacing": 15,
        "poolId": "0xc59eaeda6d1a6f031bc7e1d039772f2d675e7b4de2c8668610f4471bd60b3802"
      },
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 3600,
        "route": {
          "venue": "v4",
          "fee": 1500,
          "tickSpacing": 15,
          "poolId": "0xc59eaeda6d1a6f031bc7e1d039772f2d675e7b4de2c8668610f4471bd60b3802"
        }
      },
      "overrides": {}
    },
    {
      "ticker": "QQQ",
      "name": "Invesco QQQ • Robinhood Token",
      "underlying": "0xD5f3879160bc7c32ebb4dC785F8a4F505888de68",
      "uiMultiplier": "1000000000000000000",
      "status": "planned",
      "strikeTick": "1000000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": {
        "venue": "v4",
        "fee": 3000,
        "tickSpacing": 60,
        "poolId": "0xf9568ec0cba6e9ba30d9daabbf3e807813b8852e5737b7d83ea06529c73c9758"
      },
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 3600,
        "route": {
          "venue": "v4",
          "fee": 3000,
          "tickSpacing": 60,
          "poolId": "0xf9568ec0cba6e9ba30d9daabbf3e807813b8852e5737b7d83ea06529c73c9758"
        }
      },
      "overrides": {}
    },
    {
      "ticker": "RGTI",
      "name": "Rigetti Computing • Robinhood Token",
      "underlying": "0x284358abc07F9359f19f4b5b4aC91901Be2597Ba",
      "uiMultiplier": "1000000000000000000",
      "status": "planned",
      "strikeTick": "500000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": null,
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 21600,
        "route": null
      },
      "overrides": {}
    },
    {
      "ticker": "RKLB",
      "name": "Rocket Lab Corporation • Robinhood Token",
      "underlying": "0x3b14C39E89D60D627b42a1A4CA45b5bb45Fc12e2",
      "uiMultiplier": "1000000000000000000",
      "status": "planned",
      "strikeTick": "1000000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": null,
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 21600,
        "route": null
      },
      "overrides": {}
    },
    {
      "ticker": "SGOV",
      "name": "iShares 0-3 Month Treasury Bond • Robinhood Token",
      "underlying": "0x92FD66527192E3e61d4DDd13322Aa222DE86F9B5",
      "uiMultiplier": "1005101770003214918",
      "status": "planned",
      "strikeTick": "1000000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": null,
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 21600,
        "route": null
      },
      "overrides": {}
    },
    {
      "ticker": "SLV",
      "name": "iShares Silver Trust • Robinhood Token",
      "underlying": "0x411eFb0E7f985935DAec3D4C3ebaEa0d0AD7D89f",
      "uiMultiplier": "1000000000000000000",
      "status": "planned",
      "strikeTick": "500000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": null,
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 21600,
        "route": null
      },
      "overrides": {}
    },
    {
      "ticker": "SNDK",
      "name": "Sandisk Corporation • Robinhood Token",
      "underlying": "0xB90A19fF0Af67f7779afF50A882A9CfF42446400",
      "uiMultiplier": "1000000000000000000",
      "status": "planned",
      "strikeTick": "10000000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": null,
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 3600,
        "route": null
      },
      "overrides": {}
    },
    {
      "ticker": "SPCX",
      "name": "SpaceX • Robinhood Token",
      "underlying": "0x4a0E65A3EcceC6dBe60AE065F2e7bb85Fae35eEa",
      "uiMultiplier": "1000000000000000000",
      "status": "planned",
      "strikeTick": "1000000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": {
        "venue": "v4",
        "fee": 10000,
        "tickSpacing": 200,
        "poolId": "0xcb6ffbcc84359535c2cc0a5688c0a76520ea6e0a4820fddd3ac8d7880e576370"
      },
      "settlement": {
        "sourceCount": 2,
        "uncorroboratedDelayS": 21600,
        "route": {
          "venue": "v4",
          "fee": 10000,
          "tickSpacing": 200,
          "poolId": "0xcb6ffbcc84359535c2cc0a5688c0a76520ea6e0a4820fddd3ac8d7880e576370"
        }
      },
      "overrides": {}
    },
    {
      "ticker": "SPY",
      "name": "SPDR S&P 500 ETF Trust • Robinhood Token",
      "underlying": "0x117cc2133c37B721F49dE2A7a74833232B3B4C0C",
      "uiMultiplier": "1000000000000000000",
      "status": "planned",
      "strikeTick": "1000000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": {
        "venue": "v4",
        "fee": 500,
        "tickSpacing": 5,
        "poolId": "0xe5923c8a8be481ec89a2ca784a2bbfa4235de6d88f92260fd66b660c4babf907"
      },
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 3600,
        "route": {
          "venue": "v4",
          "fee": 500,
          "tickSpacing": 5,
          "poolId": "0xe5923c8a8be481ec89a2ca784a2bbfa4235de6d88f92260fd66b660c4babf907"
        }
      },
      "overrides": {}
    },
    {
      "ticker": "TSLA",
      "name": "Tesla • Robinhood Token",
      "underlying": "0x322F0929c4625eD5bAd873c95208D54E1c003b2d",
      "uiMultiplier": "1000000000000000000",
      "status": "planned",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": {
        "venue": "v4",
        "fee": 3000,
        "tickSpacing": 60,
        "poolId": "0x8517f8071ae5b831b738052f12125e8e3d6c158b78728aa44ce3b25e5104d32e"
      },
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 3600,
        "route": {
          "venue": "v4",
          "fee": 3000,
          "tickSpacing": 60,
          "poolId": "0x8517f8071ae5b831b738052f12125e8e3d6c158b78728aa44ce3b25e5104d32e"
        }
      },
      "overrides": {}
    },
    {
      "ticker": "TSM",
      "name": "Taiwan Semiconductor Manufacturing • Robinhood Token",
      "underlying": "0x58FfE4a942d3885bAa22D7520691F611EF09e7AA",
      "uiMultiplier": "1001463024159690554",
      "status": "planned",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": {
        "venue": "v4",
        "fee": 7500,
        "tickSpacing": 75,
        "poolId": "0x0ba5d53d2f6255f334b7c8ead4f56b6aef5af3402c5e4d11180afd38c6b85fb1"
      },
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 3600,
        "route": {
          "venue": "v4",
          "fee": 7500,
          "tickSpacing": 75,
          "poolId": "0x0ba5d53d2f6255f334b7c8ead4f56b6aef5af3402c5e4d11180afd38c6b85fb1"
        }
      },
      "overrides": {}
    },
    {
      "ticker": "USAR",
      "name": "USA Rare Earth • Robinhood Token",
      "underlying": "0xd917B029C761D264c6A312BBbcDA868658eF86a6",
      "uiMultiplier": "1000000000000000000",
      "status": "planned",
      "strikeTick": "500000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": null,
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 21600,
        "route": null
      },
      "overrides": {}
    },
    {
      "ticker": "USO",
      "name": "United States Oil Fund • Robinhood Token",
      "underlying": "0xa30FA36Db767ad9eD3f7a60fC79526fB4d56D344",
      "uiMultiplier": "1000000000000000000",
      "status": "planned",
      "strikeTick": "1000000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": null,
      "settlement": {
        "sourceCount": 1,
        "uncorroboratedDelayS": 21600,
        "route": null
      },
      "overrides": {}
    }
  ]
} as const;
