// GENERATED by indexer/scripts/gen-v2-registry.mjs from ops/markets/tier1.json.
// The production image contains indexer/ only; regenerate after any registry change.
export const V2_REGISTRY = {
  "chainId": 4663,
  "interfaceVersion": 8,
  "deployBlock": 72462898,
  "contracts": {
    "clearinghouse": "0xD33663CD8A363710daF87C78616899cED34b9374",
    "orderBook": "0x581AFCC6Da498F4D8161705E1D294a6e4fEeaeF3",
    "settlementOracle": "0x932c9BF2350633382ed6b2CB52e1c82345A3B160",
    "expiryCalendar": "0x7ae41B8b0ba2189CC59a9c124b20D9BA00177ae5",
    "keeperRewards": "0x7410FcBE201f40a731336B723E510B9131229Eb1",
    "autoRoller": "0x47dE4E61C10d3508505594575404086C5941EeD2",
    "payoutAdapter": "0x92E01EbED9A3253a7D029912546C594bD3DD2737",
    "makerVault": "0x491D26c3c3C2Eb36e9D7629f5bd6C16344972A28",
    "makerRegistry": "0xeCD6F1842E292A2B93288bb22Ac318871d7C8B1f",
    "rewardsDistributor": "0x54545581d614C40bbD4942b527d463402eb446f6",
    "accessManager": "0x3698FDcD6A29675382d287b30546B75dE9174103",
    "houseVault": "0xF9F95d999aA798fc0B60a0f85f7CCe251fe247a7",
    "houseVaultFactory": "0x4626da1A3fCf06d837dBD49708C7B658DFD08843",
    "hedger": null,
    "rewardsDistributorLender": null,
    "earnVault": "0x847794900FAE91516Cc3fbc36955C6B64a2dD609",
    "stockVenueAdapter": null,
    "stockZap": "0x0E3C7Ea59d89D6BE8bB6Af5706856C4E913a0FE7",
    "sources": {
      "chainlink": "0xC01067D7fb962AB6374DCe20E98b1DdC9086780a",
      "univ3": "0x1E2F642C8DA800ffc5c7898DF7d28A1DBfE0f70C",
      "dataStreams": "0x459a09Ea21156de69849522B1599a9e5deEF24A6"
    }
  },
  "safes": {
    "admin": "0x6f8A7B77b72511cD8939596b1659bA28C28f101B",
    "treasury": "0x014b996a084690FB27265BfAC157b04e9FeBbF4E"
  },
  "flywheel": {
    "feeSplitter": "0xb837819273097BC6D2F1AdB4AC897DFd5c5DBdf0",
    "buybackExecutor": "0xE99972FbF00a5292CecB7DB04063A35079fEE3bd",
    "deployBlock": 72462898
  },
  "fees": {
    "premiumFeeBps": 500,
    "mintFeePpm": 0,
    "allowRent": false,
    "resaleFeeBps": 0,
    "takerFeeFlat": "100000",
    "takerFeeCapBps": 1000,
    "makerRebateBps": 5000,
    "exerciseFeeBps": 25,
    "payoutSlippageBps": 30
  },
  "defaults": {
    "ladder": {
      "weekly": {
        "rungs": 5,
        "firstOtmBps": 200,
        "stepBps": 200,
        "cardTargetBps": 400
      },
      "daily": {
        "rungs": 5,
        "firstOtmBps": 100,
        "stepBps": 100,
        "cardTargetBps": 200
      }
    },
    "expiriesAhead": {
      "daily": 6,
      "weekly": 0
    }
  },
  "launchSet": {
    "note": "The v8 launch set: launch is NVDA and SPCX only. This is the AUTHORITATIVE list and it is deliberately NOT derived from `wave` or `status`. Waves mean rollout ORDER and no market moves bucket for this; the two fields answer different questions and a tool that infers the launch set from either gets a different answer. `markets` names tickers that must exist in `markets[]`; build-markets.mjs validates that and preserves this block across a rebuild.",
    "markets": [
      "NVDA",
      "SPCX"
    ]
  },
  "house": {
    "factories": [
      {
        "kind": "daily",
        "address": "0x4626da1A3fCf06d837dBD49708C7B658DFD08843",
        "deployBlock": 72467085
      }
    ],
    "vaults": [
      {
        "ticker": "NVDA",
        "kind": "daily",
        "address": "0xF9F95d999aA798fc0B60a0f85f7CCe251fe247a7"
      },
      {
        "ticker": "SPCX",
        "kind": "daily",
        "address": "0x031AB8C376C31447e766Fb95d19D2369f3806Ce1"
      }
    ]
  },
  "markets": [
    {
      "ticker": "NVDA",
      "name": "NVIDIA • Robinhood Token",
      "underlying": "0xd0601CE157Db5bdC3162BbaC2a2C8aF5320D9EEC",
      "uiMultiplier": "1000775159164630595",
      "status": "live",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": {
        "venue": "v3",
        "fee": 500
      },
      "settlement": {
        "sourceCount": 2,
        "uncorroboratedDelayS": 21600,
        "route": {
          "venue": "v3",
          "fee": 500
        }
      },
      "overrides": {}
    },
    {
      "ticker": "SPCX",
      "name": "SpaceX • Robinhood Token",
      "underlying": "0x4a0E65A3EcceC6dBe60AE065F2e7bb85Fae35eEa",
      "uiMultiplier": "1000000000000000000",
      "status": "live",
      "strikeTick": "1000000",
      "puts": false,
      "mintFeePpm": 0,
      "payoutRoute": {
        "venue": "v3",
        "fee": 500
      },
      "settlement": {
        "sourceCount": 2,
        "uncorroboratedDelayS": 21600,
        "route": {
          "venue": "v3",
          "fee": 500
        }
      },
      "overrides": {
        "expiriesAhead": {
          "daily": 0,
          "weekly": 2
        }
      }
    }
  ]
} as const;
