// GENERATED by indexer/scripts/gen-v2-registry.mjs from ops/markets/tier1.json.
// The production image contains indexer/ only; regenerate after any registry change.
export const V2_REGISTRY = {
  "interfaceVersion": 7,
  "deployBlock": 65780341,
  "contracts": {
    "clearinghouse": "0x22dEf851cD1a3B04Ad7d232bE786d76E6944d424",
    "orderBook": "0x9fcAe743C3fA0aEC7DB9b1d01e86464b85759942",
    "settlementOracle": "0xb205984b5F2F9010c2bD8aCA46d946Fe1c4F2A54",
    "expiryCalendar": "0xd0fCeD9Ee6F533aA900BEe8d0523eF4867a5784a",
    "keeperRewards": "0xFB409E6E253bcC12a65ED02B9D5aa3cAbF8f63f3",
    "autoRoller": "0xca76e9d57992904a14E31C5103454A4906ebFfee",
    "payoutAdapter": "0xf529CE3708bd2002D6bC974dFC0501c92aE72c30",
    "makerVault": "0x5EA899580B3dEB99c6866c7CD14dEDc913C8C1d0",
    "makerRegistry": "0xED816A81F8e311F78496c63c66abaA93A996cD3B",
    "rewardsDistributor": "0xc2Eea33F12e26662c66D632915fD75BCEA13BF4f",
    "sources": {
      "chainlink": "0x1a595B2F836b7B76e71C0F85ADA6186ef16fB96A",
      "univ3": "0x030f05E856c79bC215c5683DC201473e4F88a155",
      "dataStreams": "0xeC049Df6F9908374940065cec593Ac83fc1db4d2"
    }
  },
  "fees": {
    "premiumFeeBps": 0,
    "mintFeePpm": 80,
    "resaleFeeBps": 0,
    "takerFeeFlat": "100000",
    "takerFeeCapBps": 1000,
    "makerRebateBps": 5000,
    "exerciseFeeBps": 25
  },
  "defaults": {
    "ladder": {
      "weekly": {
        "rungs": 5,
        "firstOtmBps": 200,
        "stepBps": 200,
        "cardTargetBps": 400
      },
      "daily": {
        "rungs": 5,
        "firstOtmBps": 100,
        "stepBps": 100,
        "cardTargetBps": 200
      }
    }
  },
  "markets": [
    {
      "ticker": "AAPL",
      "name": "Apple • Robinhood Token",
      "underlying": "0xaF3D76f1834A1d425780943C99Ea8A608f8a93f9",
      "status": "planned",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 25
    },
    {
      "ticker": "AMD",
      "name": "AMD • Robinhood Token",
      "underlying": "0x86923f96303D656E4aa86D9d42D1e57ad2023fdC",
      "status": "planned",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 700
    },
    {
      "ticker": "AMZN",
      "name": "Amazon • Robinhood Token",
      "underlying": "0x12f190a9F9d7D37a250758b26824B97CE941bF54",
      "status": "planned",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 40
    },
    {
      "ticker": "ASML",
      "name": "ASML Holding NV • Robinhood Token",
      "underlying": "0x47F93d52cBeC7C6D2CfC080e154002370a60dAEA",
      "status": "planned",
      "strikeTick": "10000000",
      "puts": false,
      "mintFeePpm": 300
    },
    {
      "ticker": "BABA",
      "name": "Alibaba • Robinhood Token",
      "underlying": "0xad25Ac6C84D497db898fa1E8387bf6Af3532a1c4",
      "status": "planned",
      "strikeTick": "1000000",
      "puts": false,
      "mintFeePpm": 400
    },
    {
      "ticker": "CLSK",
      "name": "CleanSpark • Robinhood Token",
      "underlying": "0xcBB95BBF36099d34dA091dc6Fa6F49EfA257Cee3",
      "status": "planned",
      "strikeTick": "500000",
      "puts": false,
      "mintFeePpm": 1200
    },
    {
      "ticker": "COIN",
      "name": "Coinbase • Robinhood Token",
      "underlying": "0x6330D8C3178a418788dF01a47479c0ce7CCF450b",
      "status": "planned",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 900
    },
    {
      "ticker": "CRCL",
      "name": "Circle Internet Group • Robinhood Token",
      "underlying": "0xdF0992E440dD0be65BD8439b609d6D4366bf1CB5",
      "status": "planned",
      "strikeTick": "1000000",
      "puts": false,
      "mintFeePpm": 1400
    },
    {
      "ticker": "CRWV",
      "name": "CoreWeave • Robinhood Token",
      "underlying": "0x5f10A1C971B69e47e059e1dC91901B59b3fB49C3",
      "status": "planned",
      "strikeTick": "1000000",
      "puts": false,
      "mintFeePpm": 1400
    },
    {
      "ticker": "DELL",
      "name": "Dell • Robinhood Token",
      "underlying": "0x941AE714EC6D8130c7B75d67160Ca08f1e7d11Dd",
      "status": "planned",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 900
    },
    {
      "ticker": "EWY",
      "name": "iShares MSCI South Korea fund • Robinhood Token",
      "underlying": "0x7f0aBeF0C07280F82c6a08ead09dEd6BAE2C13Fc",
      "status": "planned",
      "strikeTick": "1000000",
      "puts": false,
      "mintFeePpm": 400
    },
    {
      "ticker": "GME",
      "name": "GameStop • Robinhood Token",
      "underlying": "0x1b0E319c6A659F002271B69dB8A7df2F911c153E",
      "status": "planned",
      "strikeTick": "500000",
      "puts": false,
      "mintFeePpm": 900
    },
    {
      "ticker": "GOOGL",
      "name": "Alphabet Class A • Robinhood Token",
      "underlying": "0x2e0847E8910a9732eB3fb1bb4b70a580ADAD4FE3",
      "status": "planned",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 60
    },
    {
      "ticker": "INTC",
      "name": "Intel • Robinhood Token",
      "underlying": "0xc72b96e0E48ecd4DC75E1e45396e26300BC39681",
      "status": "planned",
      "strikeTick": "500000",
      "puts": false,
      "mintFeePpm": 1200
    },
    {
      "ticker": "IONQ",
      "name": "IonQ • Robinhood Token",
      "underlying": "0x558378E000D634A36593E338eBacdd6207640EfE",
      "status": "planned",
      "strikeTick": "500000",
      "puts": false,
      "mintFeePpm": 1400
    },
    {
      "ticker": "META",
      "name": "Meta Platforms • Robinhood Token",
      "underlying": "0xc0D6457C16Cc70d6790Dd43521C899C87ce02f35",
      "status": "planned",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 200
    },
    {
      "ticker": "MSFT",
      "name": "Microsoft • Robinhood Token",
      "underlying": "0xe93237C50D904957Cf27E7B1133b510C669c2e74",
      "status": "planned",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 80
    },
    {
      "ticker": "MSTR",
      "name": "Strategy Inc. • Robinhood Token",
      "underlying": "0xec262a75e413fAfD0dF80480274532C79D42da09",
      "status": "planned",
      "strikeTick": "1000000",
      "puts": false,
      "mintFeePpm": 1200
    },
    {
      "ticker": "MU",
      "name": "Micron Technology • Robinhood Token",
      "underlying": "0xfF080c8ce2E5feadaCa0Da81314Ae59D232d4afD",
      "status": "planned",
      "strikeTick": "5000000",
      "puts": false,
      "mintFeePpm": 600
    },
    {
      "ticker": "NBIS",
      "name": "Nebius Group • Robinhood Token",
      "underlying": "0x9D9c6684F596F66a64C030B93A886D51Fd4D7931",
      "status": "planned",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 1500
    },
    {
      "ticker": "NVDA",
      "name": "NVIDIA • Robinhood Token",
      "underlying": "0xd0601CE157Db5bdC3162BbaC2a2C8aF5320D9EEC",
      "status": "live",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 80
    },
    {
      "ticker": "ORCL",
      "name": "Oracle • Robinhood Token",
      "underlying": "0xb0992820E760d836549ba69BC7598b4af75dEE03",
      "status": "planned",
      "strikeTick": "1000000",
      "puts": false,
      "mintFeePpm": 600
    },
    {
      "ticker": "PLTR",
      "name": "Palantir Technologies • Robinhood Token",
      "underlying": "0x894E1EC2D74FFE5AEF8Dc8A9e84686acCB964F2A",
      "status": "planned",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 400
    },
    {
      "ticker": "QQQ",
      "name": "Invesco QQQ • Robinhood Token",
      "underlying": "0xD5f3879160bc7c32ebb4dC785F8a4F505888de68",
      "status": "planned",
      "strikeTick": "1000000",
      "puts": false,
      "mintFeePpm": 10
    },
    {
      "ticker": "RGTI",
      "name": "Rigetti Computing • Robinhood Token",
      "underlying": "0x284358abc07F9359f19f4b5b4aC91901Be2597Ba",
      "status": "planned",
      "strikeTick": "500000",
      "puts": false,
      "mintFeePpm": 1200
    },
    {
      "ticker": "RKLB",
      "name": "Rocket Lab Corporation • Robinhood Token",
      "underlying": "0x3b14C39E89D60D627b42a1A4CA45b5bb45Fc12e2",
      "status": "planned",
      "strikeTick": "1000000",
      "puts": false,
      "mintFeePpm": 1000
    },
    {
      "ticker": "SGOV",
      "name": "iShares 0-3 Month Treasury Bond • Robinhood Token",
      "underlying": "0x92FD66527192E3e61d4DDd13322Aa222DE86F9B5",
      "status": "planned",
      "strikeTick": "1000000",
      "puts": false,
      "mintFeePpm": 5
    },
    {
      "ticker": "SLV",
      "name": "iShares Silver Trust • Robinhood Token",
      "underlying": "0x411eFb0E7f985935DAec3D4C3ebaEa0d0AD7D89f",
      "status": "planned",
      "strikeTick": "500000",
      "puts": false,
      "mintFeePpm": 300
    },
    {
      "ticker": "SNDK",
      "name": "Sandisk Corporation • Robinhood Token",
      "underlying": "0xB90A19fF0Af67f7779afF50A882A9CfF42446400",
      "status": "planned",
      "strikeTick": "10000000",
      "puts": false,
      "mintFeePpm": 1100
    },
    {
      "ticker": "SPCX",
      "name": "SpaceX • Robinhood Token",
      "underlying": "0x4a0E65A3EcceC6dBe60AE065F2e7bb85Fae35eEa",
      "status": "planned",
      "strikeTick": "1000000",
      "puts": false,
      "mintFeePpm": 600
    },
    {
      "ticker": "SPY",
      "name": "SPDR S&P 500 ETF Trust • Robinhood Token",
      "underlying": "0x117cc2133c37B721F49dE2A7a74833232B3B4C0C",
      "status": "planned",
      "strikeTick": "1000000",
      "puts": false,
      "mintFeePpm": 5
    },
    {
      "ticker": "TSLA",
      "name": "Tesla • Robinhood Token",
      "underlying": "0x322F0929c4625eD5bAd873c95208D54E1c003b2d",
      "status": "planned",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 300
    },
    {
      "ticker": "TSM",
      "name": "Taiwan Semiconductor Manufacturing • Robinhood Token",
      "underlying": "0x58FfE4a942d3885bAa22D7520691F611EF09e7AA",
      "status": "planned",
      "strikeTick": "2500000",
      "puts": false,
      "mintFeePpm": 40
    },
    {
      "ticker": "USAR",
      "name": "USA Rare Earth • Robinhood Token",
      "underlying": "0xd917B029C761D264c6A312BBbcDA868658eF86a6",
      "status": "planned",
      "strikeTick": "500000",
      "puts": false,
      "mintFeePpm": 1000
    },
    {
      "ticker": "USO",
      "name": "United States Oil Fund • Robinhood Token",
      "underlying": "0xa30FA36Db767ad9eD3f7a60fC79526fB4d56D344",
      "status": "planned",
      "strikeTick": "1000000",
      "puts": false,
      "mintFeePpm": 700
    }
  ]
} as const;
