/** Generated by scripts/gen-reward-epochs.mjs; do not edit. */
export type RewardEpochProjection = {
  program: string;
  epoch: number;
  root: `0x${string}`;
  total: string;
  entries: readonly { index: number; account: string; amount: string }[];
};

export const REWARD_EPOCH_FILES = [] as const satisfies readonly RewardEpochProjection[];
