/**
 * The v2 wire contract, held to the files W2 and S2 build against.
 *
 * ops/fixtures/api/v2/ holds one example response per indexer v2 route, laid out by
 * route path, generated by ops/fixtures/api/v2/gen.mjs and served by ops/fixtures/serve-v2.mjs.
 * This file proves three things about them:
 *
 * 1. SHAPE. Every file maps to exactly one entry of ROUTES and parses with that route's STRICT
 *    schema; every ROUTES entry has at least one file. A route with no fixture is a route the
 *    dapp can be built against without ever seeing its shape, and a fixture the schema rejects
 *    means the contract and its example disagree — either is the v1 bug (the dapp read keys the
 *    indexer never sent) waiting to happen again.
 * 2. MEANING. The schema cannot see that a longId is the wrong hash, that `formatted` disagrees
 *    with `raw`, or that a card promises a multiple the contracts cannot pay. So the numbers the
 *    UI will act on are recomputed here from first principles with viem, independently of the
 *    generator: series IDs per ops/shared/v2/seriesId.ts, Money per formatUnits, EIP-55 checksums,
 *    and every card per ADR-12 with the fee rules of ADR-08. The id helper is inlined on purpose
 *    (not web/lib/v2/seriesId.ts): a test that shares the code under test cannot catch it.
 * 3. NO DRIFT. `gen.mjs --check` must report the files on disk byte-identical to what the
 *    generator produces, so a hand edit to a fixture is a red test rather than a silent fork of
 *    the scenario, and the fixture server answers with the files, the headers and the error
 *    envelope the contract states.
 */
import { spawn, spawnSync } from "node:child_process";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

import { encodeAbiParameters, formatUnits, getAddress, keccak256, type Address } from "viem";
import { describe, expect, it } from "vitest";

import {
  ROUTES,
  cardSchema,
  configResponseSchema,
  errorSchema,
  healthResponseSchema,
  heroCardResponseSchema,
  cardsResponseSchema,
  marketsResponseSchema,
  seriesDetailResponseSchema,
  bookResponseSchema,
  winsResponseSchema,
  pnlResponseSchema,
  type RouteSpec,
} from "./api-schema";
import type { Card, SeriesRef } from "./api-types";

type Json = null | boolean | number | string | Json[] | { [k: string]: Json };
type JsonObject = { [k: string]: Json };

const FIXTURES = fileURLToPath(new URL("../../../ops/fixtures/api/v2/", import.meta.url));
const GEN = join(FIXTURES, "gen.mjs");
const SERVER = fileURLToPath(new URL("../../../ops/fixtures/serve-v2.mjs", import.meta.url));

// ---------------------------------------------------------------------------------------------
// Loading and route matching
// ---------------------------------------------------------------------------------------------

type Fixture = { rel: string; url: string; body: Json };

function listJson(dir: string, acc: string[] = []): string[] {
  for (const name of readdirSync(dir).sort()) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) listJson(p, acc);
    else if (name.endsWith(".json")) acc.push(p);
  }
  return acc;
}

const FILES: Fixture[] = listJson(FIXTURES).map((p) => {
  const rel = relative(FIXTURES, p).split(sep).join("/");
  return { rel, url: `/v2/${rel.slice(0, -".json".length)}`, body: JSON.parse(readFileSync(p, "utf8")) as Json };
});

const byRel = new Map(FILES.map((f) => [f.rel, f.body]));
function fixture(rel: string): Json {
  const body = byRel.get(rel);
  if (body === undefined) throw new Error(`missing fixture ${rel}`);
  return body;
}

/** The ROUTES entries a concrete path matches, with the `:param` captures. */
function matchRoutes(url: string): { spec: RouteSpec; params: Record<string, string> }[] {
  const parts = url.split("/");
  const out: { spec: RouteSpec; params: Record<string, string> }[] = [];
  for (const spec of ROUTES) {
    const pattern = spec.route.split("/");
    if (pattern.length !== parts.length) continue;
    const params: Record<string, string> = {};
    let ok = true;
    pattern.forEach((seg, i) => {
      if (seg.startsWith(":")) params[seg.slice(1)] = parts[i];
      else if (seg !== parts[i]) ok = false;
    });
    if (ok) out.push({ spec, params });
  }
  return out;
}

const isObject = (v: Json): v is JsonObject => v !== null && typeof v === "object" && !Array.isArray(v);

/** Every value in a JSON tree, with a readable path. */
function* walk(value: Json, path: string): Generator<[Json, string]> {
  yield [value, path];
  if (Array.isArray(value)) {
    for (let i = 0; i < value.length; i++) yield* walk(value[i], `${path}[${i}]`);
  } else if (isObject(value)) {
    for (const [k, v] of Object.entries(value)) yield* walk(v, `${path}.${k}`);
  }
}

function* everywhere(): Generator<[Json, string]> {
  for (const f of FILES) yield* walk(f.body, f.rel);
}

const issues = (e: { issues: { path: (string | number)[]; message: string }[] }) =>
  e.issues.map((i) => `${i.path.join(".") || "(root)"}: ${i.message}`).join("; ");

const ADDRESS_RE = /^0x[0-9a-fA-F]{40}$/;
const min = (a: bigint, b: bigint) => (a < b ? a : b);
const ceilDiv = (a: bigint, b: bigint) => (a + b - 1n) / b;

const BPS = 10_000n;

/**
 * ADR-12 card maths per unit, restated from contract OptionMath at P = T, in USDG
 * base units. Call: T = roundUp(K × (1 + bps), tick), gross = (T − K)/100, fee = min(T × feeBps /
 * 1e4 / 100, gross × 10 %). Put: T = roundDown(K × (1 − bps), tick) but at least one tick,
 * gross = (K − T)/100, fee = min((K/100) × feeBps / 1e4, gross × 10 %).
 */
function cardMath(isPut: boolean, strike: bigint, tick: bigint, cardTargetBps: number, exerciseFeeBps: number) {
  const bps = BigInt(cardTargetBps);
  const feeBps = BigInt(exerciseFeeBps);
  if (isPut) {
    const floored = ((strike * (BPS - bps)) / (BPS * tick)) * tick;
    const target = floored < tick ? tick : floored;
    const gross = (strike - target) / 100n;
    const fee = min(((strike / 100n) * feeBps) / BPS, (gross * 1000n) / BPS);
    return { target, gross, fee, payout: gross - fee };
  }
  const target = ceilDiv(strike * (BPS + bps), BPS * tick) * tick;
  const gross = (target - strike) / 100n;
  const fee = min((target * feeBps) / BPS / 100n, (gross * 1000n) / BPS);
  return { target, gross, fee, payout: gross - fee };
}

/** Long ID encoding, restated: keccak256(abi.encode(underlying, isPut, strike, expiry)) & ~1. */
function longIdOf(underlying: string, isPut: boolean, strike: bigint, expiry: number): bigint {
  const encoded = encodeAbiParameters(
    [{ type: "address" }, { type: "bool" }, { type: "uint128" }, { type: "uint40" }],
    [underlying as Address, isPut, strike, expiry],
  );
  return BigInt(keccak256(encoded)) & ~1n;
}

// ---------------------------------------------------------------------------------------------
// 1. Shape
// ---------------------------------------------------------------------------------------------

describe("ops/fixtures/api/v2: every file is one §4 route and parses strictly", () => {
  it("the directory holds the full example set and every file maps to exactly one route", () => {
    expect(FILES.length).toBeGreaterThan(100);
    for (const f of FILES) {
      const matches = matchRoutes(f.url);
      expect(matches.map((m) => m.spec.route), f.rel).toHaveLength(1);
    }
  });

  it.each(ROUTES.map((spec) => [spec.route, spec] as const))("%s has a fixture and every one parses", (_, spec) => {
    const mine = FILES.filter((f) => matchRoutes(f.url)[0]?.spec === spec);
    expect(mine.length, `no fixture for ${spec.route}`).toBeGreaterThan(0);
    for (const f of mine) {
      const r = spec.schema.safeParse(f.body);
      expect(r.success, r.success ? f.rel : `${f.rel}: ${issues(r.error)}`).toBe(true);
    }
  });

  it("route params are real: known tickers, series with files, checksummed addresses, win ids", () => {
    const markets = marketsResponseSchema.parse(fixture("markets.json"));
    const tickers = new Set(markets.map((m) => m.ticker));
    for (const f of FILES) {
      const { params } = matchRoutes(f.url)[0];
      if (params.ticker !== undefined) expect(tickers.has(params.ticker), f.rel).toBe(true);
      if (params.longId !== undefined) {
        expect(params.longId, f.rel).toMatch(/^\d+$/);
        expect(byRel.has(`series/${params.longId}.json`), f.rel).toBe(true);
      }
      if (params.address !== undefined) expect(getAddress(params.address), f.rel).toBe(params.address);
      if (params.id !== undefined) {
        const win = pnlResponseSchema.parse(f.body);
        expect(params.id, f.rel).toBe(win.id);
      }
    }
  });

  it("the schemas really are strict (a gate must be able to fail)", () => {
    const health = healthResponseSchema.parse(fixture("health.json"));
    expect(healthResponseSchema.safeParse({ ...health, extra: 1 }).success).toBe(false);
    expect(healthResponseSchema.safeParse({ ...health, block: 64418145 }).success).toBe(false);

    const card = heroCardResponseSchema.parse(fixture("cards/hero.json")).card as Card;
    const withoutMaxLoss: Partial<Card> = { ...card };
    delete withoutMaxLoss.maxLoss;
    expect(cardSchema.safeParse(withoutMaxLoss).success).toBe(false);
    const withoutPerShare: Partial<Card> = { ...card };
    delete withoutPerShare.perShare;
    expect(cardSchema.safeParse(withoutPerShare).success).toBe(false);
    expect(cardSchema.safeParse({ ...card, perShare: null }).success).toBe(true);
    expect(cardSchema.safeParse({ ...card, perShare: { ...card.perUnit, units: "100" } }).success).toBe(false);
    expect(cardSchema.safeParse({ ...card, ask: { ...card.ask, raw: "0012" } }).success).toBe(false);
    expect(cardSchema.safeParse({ ...card, ask: { ...card.ask, raw: "-1" } }).success).toBe(false);
    const lower = card.series.underlying.toLowerCase();
    expect(cardSchema.safeParse({ ...card, series: { ...card.series, underlying: lower } }).success).toBe(false);
    expect(cardSchema.safeParse({ ...card, series: { ...card.series, expiry: 1.5 } }).success).toBe(false);
    expect(errorSchema.safeParse({ error: { code: "not_found", message: "x", status: 404 } }).success).toBe(false);
  });

  it("requires a nullable series settlement time distinct from the oracle verdict", () => {
    const detail = FILES.find((f) => /^series\/\d+\.json$/.test(f.rel) &&
      isObject(f.body) && isObject(f.body.settlement) && f.body.settlement.status === "Finalized");
    expect(detail).toBeDefined();
    const body = detail!.body as JsonObject;
    const settlement = body.settlement as JsonObject;
    const withoutTime = { ...settlement };
    delete withoutTime.settledAt;
    expect(seriesDetailResponseSchema.safeParse({ ...body, settlement: withoutTime }).success).toBe(false);
    expect(seriesDetailResponseSchema.safeParse({ ...body,
      settlement: { ...settlement, settledAt: null } }).success).toBe(true);
    expect(seriesDetailResponseSchema.safeParse({ ...body,
      settlement: { ...settlement, settledAt: Number(settlement.finalizedAt) + 60 } }).success).toBe(true);
  });
});

// ---------------------------------------------------------------------------------------------
// 2. Meaning
// ---------------------------------------------------------------------------------------------

describe("ops/fixtures/api/v2: the numbers mean what the contracts mean", () => {
  it("every SeriesRef carries the on-chain ids and mintCutoff = expiry − SETTLEMENT_WINDOW", () => {
    let seen = 0;
    for (const [v, path] of everywhere()) {
      if (!isObject(v) || !("longId" in v) || !("shortId" in v) || !("underlying" in v)) continue;
      const s = v as unknown as SeriesRef;
      const longId = BigInt(s.longId);
      expect(longId, path).toBe(longIdOf(s.underlying, s.isPut, BigInt(s.strike.raw), s.expiry));
      expect(BigInt(s.shortId), path).toBe(longId | 1n);
      expect(longId & 1n, path).toBe(0n);
      expect(s.mintCutoff, path).toBe(s.expiry - 1800);
      seen += 1;
    }
    expect(seen, "the walker must actually find SeriesRefs").toBeGreaterThan(100);
  });

  it("every Money's formatted is formatUnits(raw, decimals)", () => {
    let seen = 0;
    for (const [v, path] of everywhere()) {
      if (!isObject(v) || Object.keys(v).sort().join() !== "decimals,formatted,raw") continue;
      expect(v.formatted, path).toBe(formatUnits(BigInt(v.raw as string), v.decimals as number));
      seen += 1;
    }
    expect(seen, "the walker must actually find Money").toBeGreaterThan(500);
  });

  it("every address anywhere is EIP-55 checksummed", () => {
    let seen = 0;
    for (const [v, path] of everywhere()) {
      if (typeof v !== "string" || !ADDRESS_RE.test(v)) continue;
      expect(getAddress(v), path).toBe(v);
      seen += 1;
    }
    expect(seen, "the walker must actually find addresses").toBeGreaterThan(200);
  });

  it("every longId anywhere resolves to its series, book, holders, trades and fair files", () => {
    for (const [v, path] of everywhere()) {
      if (!isObject(v) || typeof v.longId !== "string") continue;
      for (const rel of ["", "/book", "/holders", "/trades"]) {
        expect(byRel.has(`series/${v.longId}${rel}.json`), `${path} → series/${v.longId}${rel}`).toBe(true);
      }
      expect(byRel.has(`fair/${v.longId}.json`), path).toBe(true);
    }
  });

  it("card targets and payouts, by hand: calls round the target up, puts round it down (never below a tick)", () => {
    // Call NVDA K 215, tick 1, weekly 400 bps: 223.6 → T 224; gross 0.09; fee min(224 × 25 bps / 100 = 0.0056, 0.009).
    expect(cardMath(false, 215_000_000n, 1_000_000n, 400, 25)).toEqual({ target: 224_000_000n, gross: 90_000n, fee: 5_600n, payout: 84_400n });
    // Put NVDA K 215, tick 1, weekly 400 bps: 206.4 → T 206; gross 0.09; fee min(2.15 × 25 bps = 0.005375, 0.009).
    expect(cardMath(true, 215_000_000n, 1_000_000n, 400, 25)).toEqual({ target: 206_000_000n, gross: 90_000n, fee: 5_375n, payout: 84_625n });
    // Put TSLA K 355, tick 5, daily 200 bps: 347.9 → T 345; gross 0.10; fee min(3.55 × 25 bps = 0.008875, 0.01).
    expect(cardMath(true, 355_000_000n, 5_000_000n, 200, 25)).toEqual({ target: 345_000_000n, gross: 100_000n, fee: 8_875n, payout: 91_125n });
    // Put NVDA K 215, tick 1, daily 200 bps: 210.7 → T 210; gross 0.05; the 10 % cap binds: fee 0.005, not 0.005375.
    expect(cardMath(true, 215_000_000n, 1_000_000n, 200, 25)).toEqual({ target: 210_000_000n, gross: 50_000n, fee: 5_000n, payout: 45_000n });
    // Put K 5, tick 5, 400 bps: 4.8 rounds down to 0, clamped to one tick (T = K): nothing to pay.
    expect(cardMath(true, 5_000_000n, 5_000_000n, 400, 25)).toEqual({ target: 5_000_000n, gross: 0n, fee: 0n, payout: 0n });
  });

  it("cards follow ADR-12 exactly: 1-unit taker fee in the cost, exercise fee netted at the target, perShare walks the book", () => {
    const config = configResponseSchema.parse(fixture("config.json"));
    const markets = marketsResponseSchema.parse(fixture("markets.json"));
    const cards = cardsResponseSchema.parse(fixture("cards.json")).items as Card[];
    const hero = heroCardResponseSchema.parse(fixture("cards/hero.json"));
    expect(cards.length).toBeGreaterThan(10);

    const takerFeeOn = (premium: bigint) =>
      min(BigInt(config.fees.takerFeeFlat.raw), (premium * BigInt(config.fees.takerFeeCapBps)) / BPS);
    for (const card of [...cards, ...(hero.card ? [hero.card as Card] : [])]) {
      const at = `${card.series.ticker} ${card.series.strike.formatted} @${card.series.expiry}`;
      const market = markets.find((m) => m.ticker === card.series.ticker);
      expect(market, at).toBeDefined();
      const detail = seriesDetailResponseSchema.parse(fixture(`series/${card.series.longId}.json`));
      const book = bookResponseSchema.parse(fixture(`series/${card.series.longId}/book.json`));
      expect(card.series.tenor === "special", at).toBe(false);
      const ladder = card.series.tenor === "weekly" ? config.ladder.weekly : config.ladder.daily;

      const ask = BigInt(card.ask.raw);
      expect(ask % BigInt(config.constants.priceTick), at).toBe(0n);
      const unitsPerShare = BigInt(config.constants.unitsPerShare);
      const premium = ask / unitsPerShare;
      const cost = premium + takerFeeOn(premium);
      const strike = BigInt(card.series.strike.raw);
      const tick = BigInt(market!.strikeTick.raw);
      const { target, payout } = cardMath(card.series.isPut, strike, tick, ladder.cardTargetBps, detail.exerciseFeeBps);

      expect(card.target.raw, at).toBe(target.toString());
      expect(card.perUnit.cost.raw, at).toBe(cost.toString());
      expect(card.perUnit.payoutAtTarget.raw, at).toBe(payout.toString());
      expect(card.perUnit.multiple, at).toBe(Number((payout * 100n) / cost) / 100);
      expect(card.maxLoss, at).toBe("cost");

      // perShare: exactly 100 units taken cheapest first across every ask level, ONE taker fee on
      // the ticket's premium; null exactly when the whole ask side holds fewer than 100 units.
      const depth = book.asks.reduce((a, l) => a + BigInt(l.units), 0n);
      if (depth < unitsPerShare) {
        expect(card.perShare, at).toBeNull();
      } else {
        let left = unitsPerShare;
        let ticketPremium = 0n;
        for (const level of book.asks) {
          const take = min(left, BigInt(level.units));
          ticketPremium += (BigInt(level.price.raw) * take) / unitsPerShare;
          left -= take;
          if (left === 0n) break;
        }
        const shareCost = ticketPremium + takerFeeOn(ticketPremium);
        const sharePayout = payout * unitsPerShare;
        expect(card.perShare, at).not.toBeNull();
        expect(card.perShare!.cost.raw, at).toBe(shareCost.toString());
        expect(card.perShare!.payoutAtTarget.raw, at).toBe(sharePayout.toString());
        expect(card.perShare!.multiple, at).toBe(Number((sharePayout * 100n) / shareCost) / 100);
      }
      expect(card.spot, at).toEqual(market!.spot);
      expect(card.series, at).toEqual(detail.series);
      expect(card.series.status, at).toBe("open");
      // The card IS the best ask level of the served book, in take order.
      expect(card.ask, at).toEqual(book.asks[0].price);
      expect(card.unitsAvailable, at).toBe(book.asks[0].units);
      expect(card.orderIds, at).toEqual(book.asks[0].orders.map((o) => o.orderId));
    }

    const multiples = cards.map((c) => c.perUnit.multiple);
    expect(multiples, "cards sort by multiple, best first").toEqual([...multiples].sort((a, b) => b - a));
    // The hero is the best card with at least 100 units behind it; the top card is thinner, so
    // the rule is exercised, not assumed.
    const eligible = cards.find((c) => BigInt(c.unitsAvailable) >= 100n) ?? null;
    expect(hero.card).toEqual(eligible);
    expect(hero.maxMultiple).toBe(eligible ? eligible.perUnit.multiple : null);
    expect(BigInt(cards[0].unitsAvailable)).toBeLessThan(100n);
    // Both perShare forms are exercised: thin books give null, and most cards carry a ticket,
    // including one that spans two ask levels (its cost is not 100 × the best-ask premium + fee).
    const thin = cards.filter((c) => c.perShare === null).length;
    expect(thin).toBeGreaterThan(0);
    expect(thin * 2).toBeLessThan(cards.length);
    expect(hero.card?.perShare).not.toBeNull();
    const spansLevels = cards.some((c) => {
      if (c.perShare === null) return false;
      const premium = BigInt(c.ask.raw);
      return BigInt(c.perShare.cost.raw) !== premium + takerFeeOn(premium);
    });
    expect(spansLevels).toBe(true);
  });

  it("books are ordered and add up; quotes agree with them", () => {
    for (const f of FILES.filter((x) => /^series\/\d+\/book\.json$/.test(x.rel))) {
      const book = bookResponseSchema.parse(f.body);
      const prices = (side: typeof book.asks) => side.map((l) => BigInt(l.price.raw));
      const asks = prices(book.asks);
      const bids = prices(book.bids);
      expect(asks, f.rel).toEqual([...asks].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0)));
      expect(bids, f.rel).toEqual([...bids].sort((a, b) => (a > b ? -1 : a < b ? 1 : 0)));
      for (const level of [...book.asks, ...book.bids]) {
        const sum = level.orders.reduce((a, o) => a + BigInt(o.units), 0n);
        expect(level.units, f.rel).toBe(sum.toString());
      }
      for (const level of book.bids) expect(level.orders.every((o) => o.kind === "Bid"), f.rel).toBe(true);
      for (const level of book.asks) expect(level.orders.every((o) => o.kind !== "Bid"), f.rel).toBe(true);
      if (bids.length && asks.length) expect(bids[0] < asks[0], `${f.rel} is crossed`).toBe(true);

      const detail = seriesDetailResponseSchema.parse(fixture(f.rel.replace("/book.json", ".json")));
      expect(detail.quote.bestAsk, f.rel).toEqual(book.asks[0]?.price ?? null);
      expect(detail.quote.bestBid, f.rel).toEqual(book.bids[0]?.price ?? null);
      expect(detail.quote.askUnits, f.rel).toBe(book.asks[0]?.units ?? "0");
      expect(detail.quote.bidUnits, f.rel).toBe(book.bids[0]?.units ?? "0");
    }
  });

  it("series status and settlement agree (ADR-05), and settled payouts obey OptionMath", () => {
    const seen = new Set<string>();
    for (const f of FILES.filter((x) => /^series\/\d+\.json$/.test(x.rel))) {
      const d = seriesDetailResponseSchema.parse(f.body);
      seen.add(d.series.status);
      const st = d.settlement;
      switch (d.series.status) {
        case "open":
        case "cutoff":
          expect(st, f.rel).toBeNull();
          break;
        case "settling":
          expect(st?.status, f.rel).toBe("Pending");
          expect(st?.candidate, f.rel).not.toBeNull();
          break;
        case "held":
          expect(st?.status, f.rel).toBe("Held");
          break;
        case "settled": {
          expect(st?.status, f.rel).toBe("Finalized");
          const [long, fee, short] = [st?.longPayoutPerUnit, st?.feePerUnit, st?.shortPayoutPerUnit].map((m) => BigInt(m!.raw));
          expect(long + fee + short, f.rel).toBe(10n ** 16n); // collateralPerUnit of a call
          const P = BigInt(st!.price!.raw);
          const K = BigInt(d.series.strike.raw);
          const gross = P > K ? (10n ** 16n * (P - K)) / P : 0n;
          expect(long + fee, f.rel).toBe(gross);
          break;
        }
        default:
          expect(st, f.rel).not.toBeNull();
      }
    }
    // The scenario covers every state the dapp has to draw.
    expect([...seen].sort()).toEqual(["held", "open", "settled", "settling"]);
  });

  it("wins are honest: id, multiple rounded down, payout above cost, cost above the 0.10 floor, pnl page agrees", () => {
    const wins = winsResponseSchema.parse(fixture("feed/wins.json")).items;
    expect(wins.length).toBeGreaterThan(2);
    for (const w of wins) {
      const cost = BigInt(w.cost.raw);
      const payout = BigInt(w.payout.raw);
      expect(w.id).toBe(`${w.series.longId}-${w.holder}`);
      expect(w.multiple, w.id).toBe(Number((payout * 100n) / cost) / 100);
      expect(payout > cost, w.id).toBe(true);
      expect(cost >= 100_000n, w.id).toBe(true);
      expect(w.series.status, w.id).toBe("settled");
      const pnl = pnlResponseSchema.parse(fixture(`pnl/${w.id}.json`));
      const asWin = Object.fromEntries(Object.keys(w).map((k) => [k, pnl[k as keyof typeof pnl]]));
      expect(asWin, w.id).toEqual(w);
      const detail = seriesDetailResponseSchema.parse(fixture(`series/${w.series.longId}.json`));
      expect(pnl.settlementPrice, w.id).toEqual(detail.settlement?.price);
    }
  });

  it("accepts a resale-only win before the series has a settlement price", () => {
    const win = winsResponseSchema.parse(fixture("feed/wins.json")).items[0]!;
    const settled = pnlResponseSchema.parse(fixture(`pnl/${win.id}.json`));
    expect(pnlResponseSchema.safeParse({ ...settled,
      series: { ...settled.series, status: "open" }, settlementPrice: null }).success).toBe(true);
  });

  it("every list ends on its last page (the fixture server ignores ?cursor, so a pager would loop)", () => {
    for (const [v, path] of everywhere()) {
      if (isObject(v) && "nextCursor" in v) expect(v.nextCursor, path).toBeNull();
    }
  });

  it(
    "gen.mjs --check: the files are exactly what the generator writes",
    () => {
      const r = spawnSync(process.execPath, [GEN, "--check"], { encoding: "utf8" });
      expect(r.status, `${r.stdout}${r.stderr}`).toBe(0);
    },
    30_000,
  );
});

// ---------------------------------------------------------------------------------------------
// 3. The fixture server
// ---------------------------------------------------------------------------------------------

describe("ops/fixtures/serve-v2.mjs", () => {
  it(
    "serves files by route with the contract's headers and error envelope",
    async () => {
      const child = spawn(process.execPath, [SERVER, "--port", "0"], { stdio: ["ignore", "pipe", "pipe"] });
      try {
        const base = await new Promise<string>((resolve, reject) => {
          let out = "";
          const timer = setTimeout(() => reject(new Error(`server did not start: ${out}`)), 10_000);
          child.stdout.on("data", (d: Buffer) => {
            out += d.toString();
            const m = out.match(/http:\/\/localhost:(\d+)/);
            if (m) {
              clearTimeout(timer);
              resolve(`http://127.0.0.1:${m[1]}`);
            }
          });
          child.on("exit", (code) => reject(new Error(`server exited ${code}: ${out}`)));
        });

        const health = await fetch(`${base}/v2/health`);
        expect(health.status).toBe(200);
        expect(health.headers.get("cache-control")).toBe("no-store");
        expect(health.headers.get("access-control-allow-origin")).toBe("*");
        expect(healthResponseSchema.safeParse(await health.json()).success).toBe(true);

        const config = await fetch(`${base}/v2/config`);
        expect(config.status).toBe(200);
        expect(config.headers.get("cache-control")).toBe("no-store");
        expect(configResponseSchema.safeParse(await config.json()).success).toBe(true);

        const hero = heroCardResponseSchema.parse(fixture("cards/hero.json"));
        const longId = hero.card!.series.longId;
        const book = await fetch(`${base}/v2/series/${longId}/book?depth=20`);
        expect(book.status).toBe(200);
        expect(book.headers.get("cache-control")).toContain("max-age=15");
        expect(await book.json()).toEqual(fixture(`series/${longId}/book.json`));

        const missing = await fetch(`${base}/v2/series/12345`);
        expect(missing.status).toBe(404);
        const notFound = errorSchema.parse(await missing.json());
        expect(notFound.error.code).toBe("not_found");

        const post = await fetch(`${base}/v2/health`, { method: "POST" });
        expect(post.status).toBe(405);
        expect(errorSchema.safeParse(await post.json()).success).toBe(true);

        const preflight = await fetch(`${base}/v2/cards`, { method: "OPTIONS" });
        expect(preflight.status).toBe(204);
        expect(preflight.headers.get("access-control-allow-origin")).toBe("*");
      } finally {
        child.kill();
      }
    },
    30_000,
  );
});
